// Project Name: LightweightAI.Core
// File Name: RetrainingScheduler.cs
// Author: AutoGenerated
// License: All Rights Reserved. No use without consent.
// Do not remove file headers

namespace LightweightAI.Core.Training;

/// <summary>
/// Placeholder rolling retraining scheduler tracking elapsed wall time and signaling when
/// a configured retraining interval (hours -> weeks) has elapsed.
/// </summary>
public sealed class RetrainingScheduler
{
    private readonly TimeSpan _interval;
    private DateTime _next;

    public RetrainingScheduler(TimeSpan interval)
    {
        _interval = interval;
        _next = DateTime.UtcNow + _interval;
    }

    public bool ShouldRetrain(DateTime utcNow)
    {
        if (utcNow >= _next)
        {
            _next = utcNow + _interval;
            return true;
        }
        return false;
    }
}