// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ITCompanionAI.Models;

public partial class VApiMemberCurrent
{
    public Guid Id { get; set; }

    public string SemanticUid { get; set; }

    public Guid ApiFeatureId { get; set; }

    public string Name { get; set; }

    public string Kind { get; set; }

    public string MethodKind { get; set; }

    public string Accessibility { get; set; }

    public bool? IsStatic { get; set; }

    public bool? IsExtensionMethod { get; set; }

    public bool? IsAsync { get; set; }

    public bool? IsVirtual { get; set; }

    public bool? IsOverride { get; set; }

    public bool? IsAbstract { get; set; }

    public bool? IsSealed { get; set; }

    public bool? IsReadonly { get; set; }

    public bool? IsConst { get; set; }

    public bool? IsUnsafe { get; set; }

    public string ReturnTypeUid { get; set; }

    public string ReturnNullable { get; set; }

    public string GenericParameters { get; set; }

    public string GenericConstraints { get; set; }

    public string Summary { get; set; }

    public string Remarks { get; set; }

    public string Attributes { get; set; }

    public string SourceFilePath { get; set; }

    public int? SourceStartLine { get; set; }

    public int? SourceEndLine { get; set; }

    public byte[] MemberUidHash { get; set; }

    public int VersionNumber { get; set; }

    public Guid CreatedIngestionRunId { get; set; }

    public Guid? UpdatedIngestionRunId { get; set; }

    public Guid? RemovedIngestionRunId { get; set; }

    public DateTime ValidFromUtc { get; set; }

    public DateTime? ValidToUtc { get; set; }

    public bool IsActive { get; set; }

    public byte[] ContentHash { get; set; }

    public byte[] SemanticUidHash { get; set; }
}