// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ITCompanionAI.Models;

public partial class VApiFeatureCurrent
{
    public Guid Id { get; set; }

    public Guid? ApiTypeId { get; set; }

    public string SemanticUid { get; set; }

    public Guid TruthRunId { get; set; }

    public string Name { get; set; }

    public string Language { get; set; }

    public string Description { get; set; }

    public string Tags { get; set; }

    public int VersionNumber { get; set; }

    public Guid CreatedIngestionRunId { get; set; }

    public Guid UpdatedIngestionRunId { get; set; }

    public Guid? RemovedIngestionRunId { get; set; }

    public DateTime ValidFromUtc { get; set; }

    public DateTime? ValidToUtc { get; set; }

    public bool IsActive { get; set; }

    public byte[] ContentHash { get; set; }

    public byte[] SemanticUidHash { get; set; }
}