// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ITCompanionAI.Models;

public partial class VDocPageCurrent
{
    public Guid Id { get; set; }

    public string SemanticUid { get; set; }

    public Guid SourceSnapshotId { get; set; }

    public string SourcePath { get; set; }

    public string Title { get; set; }

    public string Language { get; set; }

    public string Url { get; set; }

    public string RawMarkdown { get; set; }

    public int VersionNumber { get; set; }

    public Guid CreatedIngestionRunId { get; set; }

    public Guid UpdatedIngestionRunId { get; set; }

    public Guid? RemovedIngestionRunId { get; set; }

    public DateTime ValidFromUtc { get; set; }

    public DateTime? ValidToUtc { get; set; }

    public bool IsActive { get; set; }

    public byte[] ContentHash { get; set; }

    public byte[] SemanticUidHash { get; set; }
}