ALTER DATABASE KnowledgeCurator SET READ_COMMITTED_SNAPSHOT ON;

ALTER DATABASE KnowledgeCurator SET ALLOW_SNAPSHOT_ISOLATION ON;

ALTER DATABASE KnowledgeCurator SET AUTO_CLOSE OFF;
ALTER DATABASE KnowledgeCurator SET AUTO_SHRINK OFF;

ALTER DATABASE KnowledgeCurator SET RECOVERY SIMPLE;

 --ALTER DATABASE KnowledgeCurator SET ACCELERATED_DATABASE_RECOVERY = ON;

--ALTER DATABASE KnowledgeCurator SET OPTIMIZED_LOCKING = ON;
ALTER DATABASE KnowledgeCurator SET QUERY_STORE = ON;


ALTER DATABASE KnowledgeCurator 
MODIFY FILE (NAME = "C:\Users\kcrow\KnowledgeCurator.mdf", FILEGROWTH = 256MB);

ALTER DATABASE KnowledgeCurator 
MODIFY FILE (NAME = "C:\Users\kcrow\KnowledgeCurator_log.ldf", FILEGROWTH = 256MB);

ALTER DATABASE KnowledgeCurator
MODIFY FILE (NAME = "C:\Users\kcrow\KnowledgeCurator.mdf", SIZE = 4GB);

ALTER DATABASE KnowledgeCurator SET PAGE_VERIFY CHECKSUM;

ALTER DATABASE KnowledgeCurator SET TRUSTWORTHY OFF;
ALTER DATABASE KnowledgeCurator SET PARAMETERIZATION SIMPLE;


ALTER DATABASE KnowledgeCurator SET AUTO_UPDATE_STATISTICS ON;
ALTER DATABASE KnowledgeCurator SET AUTO_UPDATE_STATISTICS_ASYNC ON;

/* 
ALTER SERVER CONFIGURATION SET MEMORY_OPTIMIZED TEMPDB_METADATA = ON;
ALTER AVAILABILITY GROUP [YourAG] MODIFY REPLICA ON 'YourReplica' WITH (READ_ONLY_ROUTING_URL = 'tcp://...');  

*/
ALTER DATABASE KnowledgeCurator SET COMPATIBILITY_LEVEL = 160;

ALTER INDEX [PK_api_type] ON dbo.api_type SET (OPTIMIZE_FOR_SEQUENTIAL_KEY = ON);


ALTER DATABASE KnowledgeCurator SET DELAYED_DURABILITY = FORCED;
ALTER DATABASE SCOPED CONFIGURATION SET TSQL_SCALAR_UDF_INLINING = ON;
ALTER DATABASE KnowledgeCurator SET READ_COMMITTED_SNAPSHOT ON;
ALTER DATABASE KnowledgeCurator SET ALLOW_SNAPSHOT_ISOLATION ON;
ALTER DATABASE KnowledgeCurator SET AUTO_CLOSE OFF;
ALTER DATABASE KnowledgeCurator SET AUTO_SHRINK OFF;
ALTER DATABASE KnowledgeCurator SET ACCELERATED_DATABASE_RECOVERY = ON;
ALTER DATABASE KnowledgeCurator SET PAGE_VERIFY CHECKSUM;
ALTER DATABASE KnowledgeCurator SET AUTO_UPDATE_STATISTICS ON;
ALTER DATABASE KnowledgeCurator SET AUTO_UPDATE_STATISTICS_ASYNC ON;
ALTER DATABASE KnowledgeCurator SET PARAMETERIZATION SIMPLE;
ALTER DATABASE KnowledgeCurator SET QUERY_STORE = ON;
ALTER DATABASE KnowledgeCurator SET TRUSTWORTHY OFF;
ALTER DATABASE KnowledgeCurator SET OPTIMIZED_LOCKING = ON;
ALTER DATABASE KnowledgeCurator SET COMPATIBILITY_LEVEL = 160;
