// Project Name: LightweightAI.Core
// File Name: FeatureEncoder.cs
// Author: AutoGenerated
// License: All Rights Reserved. No use without consent.
// Do not remove file headers

using LightweightAI.Core.Abstractions;

namespace LightweightAI.Core.Refinery;

/// <summary>
/// High level feature encoder that delegates to a concrete <see cref="IFeatureEncoder"/> (currently <see cref="OneHotEncoder"/>)
/// providing a stable location that matches the implementation matrix expectations.
/// </summary>
public sealed class FeatureEncoder
{
    private readonly OneHotEncoder _oneHot;

    public FeatureEncoder(OneHotEncoder oneHot)
    {
        _oneHot = oneHot;
    }

    public EncodedEvent Encode(RawEvent normalized) => _oneHot.Encode(normalized);
}