// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITCompanionAI;

[Table("api_member_diff")]
[Index("MemberUid", Name = "ix_api_member_diff_member")]
public partial class ApiMemberDiff
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("snapshot_diff_id")]
    public Guid SnapshotDiffId { get; set; }

    [Required]
    [Column("member_uid")]
    [StringLength(1000)]
    public string MemberUid { get; set; }

    [Column("change_kind")]
    [StringLength(200)]
    public string ChangeKind { get; set; }

    [Column("old_signature")]
    public string OldSignature { get; set; }

    [Column("new_signature")]
    public string NewSignature { get; set; }

    [Column("breaking")]
    public bool? Breaking { get; set; }

    [Column("detail_json")]
    public string DetailJson { get; set; }
}