//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 1/8/2026 10:40:40 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace ITCompanionAI.Entities
{
    public partial class ApiParameter : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private Guid _Id;

        private Guid _ApiMemberId;

        private string _Name;

        private string _TypeUid;

        private string _NullableAnnotation;

        private int? _Position;

        private string _Modifier;

        private bool? _HasDefaultValue;

        private string _DefaultValueLiteral;

        private int _VersionNumber;

        private Guid _CreatedIngestionRunId;

        private Guid _UpdatedIngestionRunId;

        private Guid? _RemovedIngestionRunId;

        private DateTime _ValidFromUtc;

        private DateTime? _ValidToUtc;

        private bool _IsActive;

        private byte[] _ContentHash;

        private byte[] _SemanticUidHash;

        private IngestionRun _IngestionRun;

        public ApiParameter()
        {
            this._IsActive = true;
            OnCreated();
        }

        public Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.SendPropertyChanging("Id");
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                }
            }
        }

        public Guid ApiMemberId
        {
            get
            {
                return this._ApiMemberId;
            }
            set
            {
                if (this._ApiMemberId != value)
                {
                    this.SendPropertyChanging("ApiMemberId");
                    this._ApiMemberId = value;
                    this.SendPropertyChanged("ApiMemberId");
                }
            }
        }

        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if (this._Name != value)
                {
                    this.SendPropertyChanging("Name");
                    this._Name = value;
                    this.SendPropertyChanged("Name");
                }
            }
        }

        public string TypeUid
        {
            get
            {
                return this._TypeUid;
            }
            set
            {
                if (this._TypeUid != value)
                {
                    this.SendPropertyChanging("TypeUid");
                    this._TypeUid = value;
                    this.SendPropertyChanged("TypeUid");
                }
            }
        }

        public string NullableAnnotation
        {
            get
            {
                return this._NullableAnnotation;
            }
            set
            {
                if (this._NullableAnnotation != value)
                {
                    this.SendPropertyChanging("NullableAnnotation");
                    this._NullableAnnotation = value;
                    this.SendPropertyChanged("NullableAnnotation");
                }
            }
        }

        public int? Position
        {
            get
            {
                return this._Position;
            }
            set
            {
                if (this._Position != value)
                {
                    this.SendPropertyChanging("Position");
                    this._Position = value;
                    this.SendPropertyChanged("Position");
                }
            }
        }

        public string Modifier
        {
            get
            {
                return this._Modifier;
            }
            set
            {
                if (this._Modifier != value)
                {
                    this.SendPropertyChanging("Modifier");
                    this._Modifier = value;
                    this.SendPropertyChanged("Modifier");
                }
            }
        }

        public bool? HasDefaultValue
        {
            get
            {
                return this._HasDefaultValue;
            }
            set
            {
                if (this._HasDefaultValue != value)
                {
                    this.SendPropertyChanging("HasDefaultValue");
                    this._HasDefaultValue = value;
                    this.SendPropertyChanged("HasDefaultValue");
                }
            }
        }

        public string DefaultValueLiteral
        {
            get
            {
                return this._DefaultValueLiteral;
            }
            set
            {
                if (this._DefaultValueLiteral != value)
                {
                    this.SendPropertyChanging("DefaultValueLiteral");
                    this._DefaultValueLiteral = value;
                    this.SendPropertyChanged("DefaultValueLiteral");
                }
            }
        }

        public int VersionNumber
        {
            get
            {
                return this._VersionNumber;
            }
            set
            {
                if (this._VersionNumber != value)
                {
                    this.SendPropertyChanging("VersionNumber");
                    this._VersionNumber = value;
                    this.SendPropertyChanged("VersionNumber");
                }
            }
        }

        public Guid CreatedIngestionRunId
        {
            get
            {
                return this._CreatedIngestionRunId;
            }
            set
            {
                if (this._CreatedIngestionRunId != value)
                {
                    this.SendPropertyChanging("CreatedIngestionRunId");
                    this._CreatedIngestionRunId = value;
                    this.SendPropertyChanged("CreatedIngestionRunId");
                }
            }
        }

        public Guid UpdatedIngestionRunId
        {
            get
            {
                return this._UpdatedIngestionRunId;
            }
            set
            {
                if (this._UpdatedIngestionRunId != value)
                {
                    this.SendPropertyChanging("UpdatedIngestionRunId");
                    this._UpdatedIngestionRunId = value;
                    this.SendPropertyChanged("UpdatedIngestionRunId");
                }
            }
        }

        public Guid? RemovedIngestionRunId
        {
            get
            {
                return this._RemovedIngestionRunId;
            }
            set
            {
                if (this._RemovedIngestionRunId != value)
                {
                    this.SendPropertyChanging("RemovedIngestionRunId");
                    this._RemovedIngestionRunId = value;
                    this.SendPropertyChanged("RemovedIngestionRunId");
                }
            }
        }

        public DateTime ValidFromUtc
        {
            get
            {
                return this._ValidFromUtc;
            }
            set
            {
                if (this._ValidFromUtc != value)
                {
                    this.SendPropertyChanging("ValidFromUtc");
                    this._ValidFromUtc = value;
                    this.SendPropertyChanged("ValidFromUtc");
                }
            }
        }

        public DateTime? ValidToUtc
        {
            get
            {
                return this._ValidToUtc;
            }
            set
            {
                if (this._ValidToUtc != value)
                {
                    this.SendPropertyChanging("ValidToUtc");
                    this._ValidToUtc = value;
                    this.SendPropertyChanged("ValidToUtc");
                }
            }
        }

        public bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                if (this._IsActive != value)
                {
                    this.SendPropertyChanging("IsActive");
                    this._IsActive = value;
                    this.SendPropertyChanged("IsActive");
                }
            }
        }

        public byte[] ContentHash
        {
            get
            {
                return this._ContentHash;
            }
            set
            {
                if (this._ContentHash != value)
                {
                    this.SendPropertyChanging("ContentHash");
                    this._ContentHash = value;
                    this.SendPropertyChanged("ContentHash");
                }
            }
        }

        public byte[] SemanticUidHash
        {
            get
            {
                return this._SemanticUidHash;
            }
            set
            {
                if (this._SemanticUidHash != value)
                {
                    this.SendPropertyChanging("SemanticUidHash");
                    this._SemanticUidHash = value;
                    this.SendPropertyChanged("SemanticUidHash");
                }
            }
        }


        public virtual IngestionRun IngestionRun
        {
            get
            {
                return this._IngestionRun;
            }
            set
            {
                if (this._IngestionRun != value)
                {
                    this.SendPropertyChanging("IngestionRun");
                    this._IngestionRun = value;
                    this.SendPropertyChanged("IngestionRun");
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
