// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITCompanionAI;

[Table("api_parameter")]
[Index("ContentHash", Name = "ix_api_parameter_content_hash")]
[Index("ApiMemberId", "Position", "IsActive", Name = "ix_api_parameter_member_position_active")]
[Index("ApiMemberId", "Position", "VersionNumber", Name = "uq_api_parameter_member_position_version", IsUnique = true)]
public partial class ApiParameter
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("api_member_id")]
    public Guid ApiMemberId { get; set; }

    [Column("name")]
    [StringLength(200)]
    public string Name { get; set; }

    [Column("type_uid")]
    [StringLength(1000)]
    public string TypeUid { get; set; }

    [Column("nullable_annotation")]
    [StringLength(50)]
    public string NullableAnnotation { get; set; }

    [Column("position")]
    public int? Position { get; set; }

    [Column("modifier")]
    [StringLength(50)]
    public string Modifier { get; set; }

    [Column("has_default_value")]
    public bool? HasDefaultValue { get; set; }

    [Column("default_value_literal")]
    public string DefaultValueLiteral { get; set; }

    [Column("version_number")]
    public int VersionNumber { get; set; }

    [Column("created_ingestion_run_id")]
    public Guid CreatedIngestionRunId { get; set; }

    [Column("updated_ingestion_run_id")]
    public Guid UpdatedIngestionRunId { get; set; }

    [Column("removed_ingestion_run_id")]
    public Guid? RemovedIngestionRunId { get; set; }

    [Column("valid_from_utc")]
    public DateTime ValidFromUtc { get; set; }

    [Column("valid_to_utc")]
    public DateTime? ValidToUtc { get; set; }

    [Column("is_active")]
    public bool IsActive { get; set; }

    [Column("content_hash")]
    [MaxLength(32)]
    public byte[] ContentHash { get; set; }

    [Column("semantic_uid_hash")]
    [MaxLength(32)]
    public byte[] SemanticUidHash { get; set; }

    [ForeignKey("CreatedIngestionRunId")]
    [InverseProperty("ApiParameters")]
    public virtual IngestionRun CreatedIngestionRun { get; set; }
}