// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITCompanionAI;

[Table("doc_page")]
[Index("ContentHash", Name = "ix_doc_page_content_hash")]
[Index("SemanticUid", "IsActive", Name = "ix_doc_page_semantic_active")]
[Index("SemanticUid", "ValidFromUtc", Name = "ix_doc_page_semantic_valid_from")]
[Index("SemanticUid", "VersionNumber", Name = "uq_doc_page_semantic_version", IsUnique = true)]
public partial class DocPage
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Required]
    [Column("semantic_uid")]
    [StringLength(1000)]
    public string SemanticUid { get; set; }

    [Column("source_snapshot_id")]
    public Guid SourceSnapshotId { get; set; }

    [Column("source_path")]
    public string SourcePath { get; set; }

    [Column("title")]
    [StringLength(400)]
    public string Title { get; set; }

    [Column("language")]
    [StringLength(200)]
    public string Language { get; set; }

    [Column("url")]
    public string Url { get; set; }

    [Column("raw_markdown")]
    public string RawMarkdown { get; set; }

    [Column("version_number")]
    public int VersionNumber { get; set; }

    [Column("created_ingestion_run_id")]
    public Guid CreatedIngestionRunId { get; set; }

    [Column("updated_ingestion_run_id")]
    public Guid? UpdatedIngestionRunId { get; set; }

    [Column("removed_ingestion_run_id")]
    public Guid? RemovedIngestionRunId { get; set; }

    [Column("valid_from_utc")]
    public DateTime ValidFromUtc { get; set; }

    [Column("valid_to_utc")]
    public DateTime? ValidToUtc { get; set; }

    [Column("is_active")]
    public bool IsActive { get; set; }

    [Column("content_hash")]
    [MaxLength(32)]
    public byte[] ContentHash { get; set; }

    [Column("semantic_uid_hash")]
    [MaxLength(32)]
    public byte[] SemanticUidHash { get; set; }

    [Column("raw_page_source")]
    public string RawPageSource { get; set; }

    [ForeignKey("CreatedIngestionRunId")]
    [InverseProperty("DocPages")]
    public virtual IngestionRun CreatedIngestionRun { get; set; }

    [InverseProperty("DocPage")]
    public virtual ICollection<DocSection> DocSections { get; set; } = new List<DocSection>();

    [ForeignKey("SourceSnapshotId")]
    [InverseProperty("DocPages")]
    public virtual SourceSnapshot SourceSnapshot { get; set; }
}