//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 1/8/2026 10:40:40 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace ITCompanionAI.Entities
{
    public partial class DocSection : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private Guid _Id;

        private Guid _DocPageId;

        private string _SemanticUid;

        private string _Heading;

        private int? _Level;

        private string _ContentMarkdown;

        private int? _OrderIndex;

        private int _VersionNumber;

        private Guid _CreatedIngestionRunId;

        private Guid _UpdatedIngestionRunId;

        private Guid? _RemovedIngestionRunId;

        private DateTime _ValidFromUtc;

        private DateTime? _ValidToUtc;

        private bool _IsActive;

        private byte[] _ContentHash;

        private byte[] _SemanticUidHash;

        private IngestionRun _IngestionRun;

        public DocSection()
        {
            this._IsActive = true;
            OnCreated();
        }

        public Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.SendPropertyChanging("Id");
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                }
            }
        }

        public Guid DocPageId
        {
            get
            {
                return this._DocPageId;
            }
            set
            {
                if (this._DocPageId != value)
                {
                    this.SendPropertyChanging("DocPageId");
                    this._DocPageId = value;
                    this.SendPropertyChanged("DocPageId");
                }
            }
        }

        public string SemanticUid
        {
            get
            {
                return this._SemanticUid;
            }
            set
            {
                if (this._SemanticUid != value)
                {
                    this.SendPropertyChanging("SemanticUid");
                    this._SemanticUid = value;
                    this.SendPropertyChanged("SemanticUid");
                }
            }
        }

        public string Heading
        {
            get
            {
                return this._Heading;
            }
            set
            {
                if (this._Heading != value)
                {
                    this.SendPropertyChanging("Heading");
                    this._Heading = value;
                    this.SendPropertyChanged("Heading");
                }
            }
        }

        public int? Level
        {
            get
            {
                return this._Level;
            }
            set
            {
                if (this._Level != value)
                {
                    this.SendPropertyChanging("Level");
                    this._Level = value;
                    this.SendPropertyChanged("Level");
                }
            }
        }

        public string ContentMarkdown
        {
            get
            {
                return this._ContentMarkdown;
            }
            set
            {
                if (this._ContentMarkdown != value)
                {
                    this.SendPropertyChanging("ContentMarkdown");
                    this._ContentMarkdown = value;
                    this.SendPropertyChanged("ContentMarkdown");
                }
            }
        }

        public int? OrderIndex
        {
            get
            {
                return this._OrderIndex;
            }
            set
            {
                if (this._OrderIndex != value)
                {
                    this.SendPropertyChanging("OrderIndex");
                    this._OrderIndex = value;
                    this.SendPropertyChanged("OrderIndex");
                }
            }
        }

        public int VersionNumber
        {
            get
            {
                return this._VersionNumber;
            }
            set
            {
                if (this._VersionNumber != value)
                {
                    this.SendPropertyChanging("VersionNumber");
                    this._VersionNumber = value;
                    this.SendPropertyChanged("VersionNumber");
                }
            }
        }

        public Guid CreatedIngestionRunId
        {
            get
            {
                return this._CreatedIngestionRunId;
            }
            set
            {
                if (this._CreatedIngestionRunId != value)
                {
                    this.SendPropertyChanging("CreatedIngestionRunId");
                    this._CreatedIngestionRunId = value;
                    this.SendPropertyChanged("CreatedIngestionRunId");
                }
            }
        }

        public Guid UpdatedIngestionRunId
        {
            get
            {
                return this._UpdatedIngestionRunId;
            }
            set
            {
                if (this._UpdatedIngestionRunId != value)
                {
                    this.SendPropertyChanging("UpdatedIngestionRunId");
                    this._UpdatedIngestionRunId = value;
                    this.SendPropertyChanged("UpdatedIngestionRunId");
                }
            }
        }

        public Guid? RemovedIngestionRunId
        {
            get
            {
                return this._RemovedIngestionRunId;
            }
            set
            {
                if (this._RemovedIngestionRunId != value)
                {
                    this.SendPropertyChanging("RemovedIngestionRunId");
                    this._RemovedIngestionRunId = value;
                    this.SendPropertyChanged("RemovedIngestionRunId");
                }
            }
        }

        public DateTime ValidFromUtc
        {
            get
            {
                return this._ValidFromUtc;
            }
            set
            {
                if (this._ValidFromUtc != value)
                {
                    this.SendPropertyChanging("ValidFromUtc");
                    this._ValidFromUtc = value;
                    this.SendPropertyChanged("ValidFromUtc");
                }
            }
        }

        public DateTime? ValidToUtc
        {
            get
            {
                return this._ValidToUtc;
            }
            set
            {
                if (this._ValidToUtc != value)
                {
                    this.SendPropertyChanging("ValidToUtc");
                    this._ValidToUtc = value;
                    this.SendPropertyChanged("ValidToUtc");
                }
            }
        }

        public bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                if (this._IsActive != value)
                {
                    this.SendPropertyChanging("IsActive");
                    this._IsActive = value;
                    this.SendPropertyChanged("IsActive");
                }
            }
        }

        public byte[] ContentHash
        {
            get
            {
                return this._ContentHash;
            }
            set
            {
                if (this._ContentHash != value)
                {
                    this.SendPropertyChanging("ContentHash");
                    this._ContentHash = value;
                    this.SendPropertyChanged("ContentHash");
                }
            }
        }

        public byte[] SemanticUidHash
        {
            get
            {
                return this._SemanticUidHash;
            }
            set
            {
                if (this._SemanticUidHash != value)
                {
                    this.SendPropertyChanging("SemanticUidHash");
                    this._SemanticUidHash = value;
                    this.SendPropertyChanged("SemanticUidHash");
                }
            }
        }


        public virtual IngestionRun IngestionRun
        {
            get
            {
                return this._IngestionRun;
            }
            set
            {
                if (this._IngestionRun != value)
                {
                    this.SendPropertyChanging("IngestionRun");
                    this._IngestionRun = value;
                    this.SendPropertyChanged("IngestionRun");
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
