// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITCompanionAI;

[Table("doc_section")]
[Index("ContentHash", Name = "ix_doc_section_content_hash")]
[Index("DocPageId", "OrderIndex", Name = "ix_doc_section_doc_page_order")]
[Index("SemanticUid", "IsActive", Name = "ix_doc_section_semantic_active")]
[Index("SemanticUid", "VersionNumber", Name = "uq_doc_section_semantic_version", IsUnique = true)]
public partial class DocSection
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("doc_page_id")]
    public Guid DocPageId { get; set; }

    [Required]
    [Column("semantic_uid")]
    [StringLength(1000)]
    public string SemanticUid { get; set; }

    [Column("heading")]
    [StringLength(400)]
    public string Heading { get; set; }

    [Column("level")]
    public int? Level { get; set; }

    [Column("content_markdown")]
    public string ContentMarkdown { get; set; }

    [Column("order_index")]
    public int? OrderIndex { get; set; }

    [Column("version_number")]
    public int VersionNumber { get; set; }

    [Column("created_ingestion_run_id")]
    public Guid CreatedIngestionRunId { get; set; }

    [Column("updated_ingestion_run_id")]
    public Guid? UpdatedIngestionRunId { get; set; }

    [Column("removed_ingestion_run_id")]
    public Guid? RemovedIngestionRunId { get; set; }

    [Column("valid_from_utc")]
    public DateTime ValidFromUtc { get; set; }

    [Column("valid_to_utc")]
    public DateTime? ValidToUtc { get; set; }

    [Column("is_active")]
    public bool IsActive { get; set; }

    [Column("content_hash")]
    [MaxLength(32)]
    public byte[] ContentHash { get; set; }

    [Column("semantic_uid_hash")]
    [MaxLength(32)]
    public byte[] SemanticUidHash { get; set; }

    [InverseProperty("DocSection")]
    public virtual ICollection<CodeBlock> CodeBlocks { get; set; } = new List<CodeBlock>();

    [ForeignKey("CreatedIngestionRunId")]
    [InverseProperty("DocSectionCreatedIngestionRuns")]
    public virtual IngestionRun CreatedIngestionRun { get; set; }

    [ForeignKey("DocPageId")]
    [InverseProperty("DocSections")]
    public virtual DocPage DocPage { get; set; }

    [ForeignKey("RemovedIngestionRunId")]
    [InverseProperty("DocSectionRemovedIngestionRuns")]
    public virtual IngestionRun RemovedIngestionRun { get; set; }

    [ForeignKey("UpdatedIngestionRunId")]
    [InverseProperty("DocSectionUpdatedIngestionRuns")]
    public virtual IngestionRun UpdatedIngestionRun { get; set; }
}