// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITCompanionAI;

[Table("execution_result")]
[Index("SampleUid", "Status", Name = "ix_execution_result_sample_status")]
public partial class ExecutionResult
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("execution_run_id")]
    public Guid ExecutionRunId { get; set; }

    [Required]
    [Column("sample_uid")]
    [StringLength(1000)]
    public string SampleUid { get; set; }

    [Column("status")]
    [StringLength(100)]
    public string Status { get; set; }

    [Column("build_log")]
    public string BuildLog { get; set; }

    [Column("run_log")]
    public string RunLog { get; set; }

    [Column("exception_json")]
    public string ExceptionJson { get; set; }

    [Column("duration_ms")]
    public int? DurationMs { get; set; }
}