// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITCompanionAI;

[Table("feature_doc_link")]
[Index("DocUid", "SectionUid", Name = "ix_feature_doc_link_doc")]
[Index("FeatureId", Name = "ix_feature_doc_link_feature")]
public partial class FeatureDocLink
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("feature_id")]
    public Guid FeatureId { get; set; }

    [Required]
    [Column("doc_uid")]
    [StringLength(1000)]
    public string DocUid { get; set; }

    [Column("section_uid")]
    [StringLength(1000)]
    public string SectionUid { get; set; }
}