//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 1/8/2026 10:40:40 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace ITCompanionAI.EFModels;

public partial class FeatureTypeLink : INotifyPropertyChanging, INotifyPropertyChanged {

    private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

    private Guid _Id;

    private Guid _FeatureId;

    private string _TypeUid;

    private string _Role;

    public FeatureTypeLink()
    {
        OnCreated();
    }

    public Guid Id
    {
        get
        {
            return this._Id;
        }
        set
        {
            if (this._Id != value)
            {
                this.SendPropertyChanging("Id");
                this._Id = value;
                this.SendPropertyChanged("Id");
            }
        }
    }

    public Guid FeatureId
    {
        get
        {
            return this._FeatureId;
        }
        set
        {
            if (this._FeatureId != value)
            {
                this.SendPropertyChanging("FeatureId");
                this._FeatureId = value;
                this.SendPropertyChanged("FeatureId");
            }
        }
    }

    public string TypeUid
    {
        get
        {
            return this._TypeUid;
        }
        set
        {
            if (this._TypeUid != value)
            {
                this.SendPropertyChanging("TypeUid");
                this._TypeUid = value;
                this.SendPropertyChanged("TypeUid");
            }
        }
    }

    public string Role
    {
        get
        {
            return this._Role;
        }
        set
        {
            if (this._Role != value)
            {
                this.SendPropertyChanging("Role");
                this._Role = value;
                this.SendPropertyChanged("Role");
            }
        }
    }

    #region Extensibility Method Definitions

    partial void OnCreated();

    #endregion

    public virtual event PropertyChangingEventHandler PropertyChanging;

    public virtual event PropertyChangedEventHandler PropertyChanged;

    protected virtual void SendPropertyChanging()
    {
        var handler = this.PropertyChanging;
        if (handler != null)
            handler(this, emptyChangingEventArgs);
    }

    protected virtual void SendPropertyChanging(System.String propertyName) 
    {
        var handler = this.PropertyChanging;
        if (handler != null)
            handler(this, new PropertyChangingEventArgs(propertyName));
    }

    protected virtual void SendPropertyChanged(System.String propertyName)
    {
        var handler = this.PropertyChanged;
        if (handler != null)
            handler(this, new PropertyChangedEventArgs(propertyName));
    }
}