// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITCompanionAI;

[Table("feature_type_link")]
[Index("FeatureId", Name = "ix_feature_type_link_feature")]
[Index("TypeUid", Name = "ix_feature_type_link_type")]
public partial class FeatureTypeLink
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("feature_id")]
    public Guid FeatureId { get; set; }

    [Required]
    [Column("type_uid")]
    [StringLength(1000)]
    public string TypeUid { get; set; }

    [Column("role")]
    [StringLength(50)]
    public string Role { get; set; }
}