// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using ITCompanionAI;

namespace ITCompanionAI
{
    public partial class KBContext
    {

        [DbFunction("fn_ComputeContentHash256", "dbo")]
        public static byte[] fn_ComputeContentHash256(string Input)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("fn_GetDocPageAsOf", "dbo")]
        public IQueryable<fn_GetDocPageAsOfResult> fn_GetDocPageAsOf(string SemanticUid, DateTime? AsOfUtc)
        {
            return FromExpression(() => fn_GetDocPageAsOf(SemanticUid, AsOfUtc));
        }

        [DbFunction("fn_GetFeatureAsOf", "dbo")]
        public IQueryable<fn_GetFeatureAsOfResult> fn_GetFeatureAsOf(string SemanticUid, DateTime? AsOfUtc)
        {
            return FromExpression(() => fn_GetFeatureAsOf(SemanticUid, AsOfUtc));
        }

        [DbFunction("fn_GetMemberAsOf", "dbo")]
        public IQueryable<fn_GetMemberAsOfResult> fn_GetMemberAsOf(string SemanticUid, DateTime? AsOfUtc)
        {
            return FromExpression(() => fn_GetMemberAsOf(SemanticUid, AsOfUtc));
        }

        [DbFunction("fn_GetTypeAsOf", "dbo")]
        public IQueryable<fn_GetTypeAsOfResult> fn_GetTypeAsOf(string SemanticUid, DateTime? AsOfUtc)
        {
            return FromExpression(() => fn_GetTypeAsOf(SemanticUid, AsOfUtc));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<fn_GetDocPageAsOfResult>().HasNoKey();
            modelBuilder.Entity<fn_GetFeatureAsOfResult>().HasNoKey();
            modelBuilder.Entity<fn_GetMemberAsOfResult>().HasNoKey();
            modelBuilder.Entity<fn_GetTypeAsOfResult>().HasNoKey();
        }
    }
}
