//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 1.25
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.Practices.EnterpriseLibrary.Validation.Validators;

namespace ITCompanionAI.Entities
{
    public partial class IngestionRun : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private Guid _Id;

        private DateTime _TimestampUtc;

        private string _SchemaVersion;

        private string _Notes;

        private ICollection<ApiFeature> _ApiFeatures_CreatedIngestionRunId;

        private ICollection<ApiFeature> _ApiFeatures_UpdatedIngestionRunId;

        private ICollection<ApiFeature> _ApiFeatures_RemovedIngestionRunId;

        private ICollection<ApiMember> _ApiMembers_CreatedIngestionRunId;

        private ICollection<ApiMember> _ApiMembers_UpdatedIngestionRunId;

        private ICollection<ApiMember> _ApiMembers_RemovedIngestionRunId;

        private ICollection<ApiType> _ApiTypes_CreatedIngestionRunId;

        private ICollection<ApiType> _ApiTypes_UpdatedIngestionRunId;

        private ICollection<ApiType> _ApiTypes_RemovedIngestionRunId;

        private ICollection<CodeBlock> _CodeBlocks_CreatedIngestionRunId;

        private ICollection<CodeBlock> _CodeBlocks_UpdatedIngestionRunId;

        private ICollection<CodeBlock> _CodeBlocks_RemovedIngestionRunId;

        private ICollection<DocPage> _DocPages_CreatedIngestionRunId;

        private ICollection<DocPage> _DocPages_UpdatedIngestionRunId;

        private ICollection<DocPage> _DocPages_RemovedIngestionRunId;

        private ICollection<DocSection> _DocSections_CreatedIngestionRunId;

        private ICollection<DocSection> _DocSections_UpdatedIngestionRunId;

        private ICollection<DocSection> _DocSections_RemovedIngestionRunId;

        private ICollection<SourceSnapshot> _SourceSnapshots;

        public IngestionRun()
        {
            this._ApiFeatures_CreatedIngestionRunId = new List<ApiFeature>();
            this._ApiFeatures_UpdatedIngestionRunId = new List<ApiFeature>();
            this._ApiFeatures_RemovedIngestionRunId = new List<ApiFeature>();
            this._ApiMembers_CreatedIngestionRunId = new List<ApiMember>();
            this._ApiMembers_UpdatedIngestionRunId = new List<ApiMember>();
            this._ApiMembers_RemovedIngestionRunId = new List<ApiMember>();
            this._ApiTypes_CreatedIngestionRunId = new List<ApiType>();
            this._ApiTypes_UpdatedIngestionRunId = new List<ApiType>();
            this._ApiTypes_RemovedIngestionRunId = new List<ApiType>();
            this._CodeBlocks_CreatedIngestionRunId = new List<CodeBlock>();
            this._CodeBlocks_UpdatedIngestionRunId = new List<CodeBlock>();
            this._CodeBlocks_RemovedIngestionRunId = new List<CodeBlock>();
            this._DocPages_CreatedIngestionRunId = new List<DocPage>();
            this._DocPages_UpdatedIngestionRunId = new List<DocPage>();
            this._DocPages_RemovedIngestionRunId = new List<DocPage>();
            this._DocSections_CreatedIngestionRunId = new List<DocSection>();
            this._DocSections_UpdatedIngestionRunId = new List<DocSection>();
            this._DocSections_RemovedIngestionRunId = new List<DocSection>();
            this._SourceSnapshots = new List<SourceSnapshot>();
            OnCreated();
        }

        [NotNullValidator()]
        public Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging("Id");
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

        [NotNullValidator()]
        public DateTime TimestampUtc
        {
            get
            {
                return this._TimestampUtc;
            }
            set
            {
                if (this._TimestampUtc != value)
                {
                    this.OnTimestampUtcChanging(value);
                    this.SendPropertyChanging("TimestampUtc");
                    this._TimestampUtc = value;
                    this.SendPropertyChanged("TimestampUtc");
                    this.OnTimestampUtcChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 200,  RangeBoundaryType.Inclusive)]
        [NotNullValidator()]
        public string SchemaVersion
        {
            get
            {
                return this._SchemaVersion;
            }
            set
            {
                if (this._SchemaVersion != value)
                {
                    this.OnSchemaVersionChanging(value);
                    this.SendPropertyChanging("SchemaVersion");
                    this._SchemaVersion = value;
                    this.SendPropertyChanged("SchemaVersion");
                    this.OnSchemaVersionChanged();
                }
            }
        }

        public string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                if (this._Notes != value)
                {
                    this.OnNotesChanging(value);
                    this.SendPropertyChanging("Notes");
                    this._Notes = value;
                    this.SendPropertyChanged("Notes");
                    this.OnNotesChanged();
                }
            }
        }


        public virtual ICollection<ApiFeature> ApiFeatures_CreatedIngestionRunId
        {
            get
            {
                return this._ApiFeatures_CreatedIngestionRunId;
            }
            set
            {
                this._ApiFeatures_CreatedIngestionRunId = value;
            }
        }


        public virtual ICollection<ApiFeature> ApiFeatures_UpdatedIngestionRunId
        {
            get
            {
                return this._ApiFeatures_UpdatedIngestionRunId;
            }
            set
            {
                this._ApiFeatures_UpdatedIngestionRunId = value;
            }
        }


        public virtual ICollection<ApiFeature> ApiFeatures_RemovedIngestionRunId
        {
            get
            {
                return this._ApiFeatures_RemovedIngestionRunId;
            }
            set
            {
                this._ApiFeatures_RemovedIngestionRunId = value;
            }
        }


        public virtual ICollection<ApiMember> ApiMembers_CreatedIngestionRunId
        {
            get
            {
                return this._ApiMembers_CreatedIngestionRunId;
            }
            set
            {
                this._ApiMembers_CreatedIngestionRunId = value;
            }
        }


        public virtual ICollection<ApiMember> ApiMembers_UpdatedIngestionRunId
        {
            get
            {
                return this._ApiMembers_UpdatedIngestionRunId;
            }
            set
            {
                this._ApiMembers_UpdatedIngestionRunId = value;
            }
        }


        public virtual ICollection<ApiMember> ApiMembers_RemovedIngestionRunId
        {
            get
            {
                return this._ApiMembers_RemovedIngestionRunId;
            }
            set
            {
                this._ApiMembers_RemovedIngestionRunId = value;
            }
        }


        public virtual ICollection<ApiType> ApiTypes_CreatedIngestionRunId
        {
            get
            {
                return this._ApiTypes_CreatedIngestionRunId;
            }
            set
            {
                this._ApiTypes_CreatedIngestionRunId = value;
            }
        }


        public virtual ICollection<ApiType> ApiTypes_UpdatedIngestionRunId
        {
            get
            {
                return this._ApiTypes_UpdatedIngestionRunId;
            }
            set
            {
                this._ApiTypes_UpdatedIngestionRunId = value;
            }
        }


        public virtual ICollection<ApiType> ApiTypes_RemovedIngestionRunId
        {
            get
            {
                return this._ApiTypes_RemovedIngestionRunId;
            }
            set
            {
                this._ApiTypes_RemovedIngestionRunId = value;
            }
        }


        public virtual ICollection<CodeBlock> CodeBlocks_CreatedIngestionRunId
        {
            get
            {
                return this._CodeBlocks_CreatedIngestionRunId;
            }
            set
            {
                this._CodeBlocks_CreatedIngestionRunId = value;
            }
        }


        public virtual ICollection<CodeBlock> CodeBlocks_UpdatedIngestionRunId
        {
            get
            {
                return this._CodeBlocks_UpdatedIngestionRunId;
            }
            set
            {
                this._CodeBlocks_UpdatedIngestionRunId = value;
            }
        }


        public virtual ICollection<CodeBlock> CodeBlocks_RemovedIngestionRunId
        {
            get
            {
                return this._CodeBlocks_RemovedIngestionRunId;
            }
            set
            {
                this._CodeBlocks_RemovedIngestionRunId = value;
            }
        }


        public virtual ICollection<DocPage> DocPages_CreatedIngestionRunId
        {
            get
            {
                return this._DocPages_CreatedIngestionRunId;
            }
            set
            {
                this._DocPages_CreatedIngestionRunId = value;
            }
        }


        public virtual ICollection<DocPage> DocPages_UpdatedIngestionRunId
        {
            get
            {
                return this._DocPages_UpdatedIngestionRunId;
            }
            set
            {
                this._DocPages_UpdatedIngestionRunId = value;
            }
        }


        public virtual ICollection<DocPage> DocPages_RemovedIngestionRunId
        {
            get
            {
                return this._DocPages_RemovedIngestionRunId;
            }
            set
            {
                this._DocPages_RemovedIngestionRunId = value;
            }
        }


        public virtual ICollection<DocSection> DocSections_CreatedIngestionRunId
        {
            get
            {
                return this._DocSections_CreatedIngestionRunId;
            }
            set
            {
                this._DocSections_CreatedIngestionRunId = value;
            }
        }


        public virtual ICollection<DocSection> DocSections_UpdatedIngestionRunId
        {
            get
            {
                return this._DocSections_UpdatedIngestionRunId;
            }
            set
            {
                this._DocSections_UpdatedIngestionRunId = value;
            }
        }


        public virtual ICollection<DocSection> DocSections_RemovedIngestionRunId
        {
            get
            {
                return this._DocSections_RemovedIngestionRunId;
            }
            set
            {
                this._DocSections_RemovedIngestionRunId = value;
            }
        }


        public virtual ICollection<SourceSnapshot> SourceSnapshots
        {
            get
            {
                return this._SourceSnapshots;
            }
            set
            {
                this._SourceSnapshots = value;
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();
        partial void OnIdChanging(Guid value);

        partial void OnIdChanged();
        partial void OnTimestampUtcChanging(DateTime value);

        partial void OnTimestampUtcChanged();
        partial void OnSchemaVersionChanging(string value);

        partial void OnSchemaVersionChanged();
        partial void OnNotesChanging(string value);

        partial void OnNotesChanged();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
