//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 1.25
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.Practices.EnterpriseLibrary.Validation.Validators;

namespace ITCompanionAI.Entities
{
    public partial class Sample : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private Guid _Id;

        private Guid _SampleRunId;

        private string _SampleUid;

        private string _FeatureUid;

        private string _Language;

        private string _Code;

        private string _EntryPoint;

        private string _TargetFramework;

        private string _PackageReferences;

        private string _DerivedFromCodeUid;

        private string _Tags;

        private SampleRun _SampleRun;

        private ICollection<SampleApiMemberLink> _SampleApiMemberLinks;

        public Sample()
        {
            this._SampleApiMemberLinks = new List<SampleApiMemberLink>();
            OnCreated();
        }

        [NotNullValidator()]
        public Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging("Id");
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

        [NotNullValidator()]
        public Guid SampleRunId
        {
            get
            {
                return this._SampleRunId;
            }
            set
            {
                if (this._SampleRunId != value)
                {
                    this.OnSampleRunIdChanging(value);
                    this.SendPropertyChanging("SampleRunId");
                    this._SampleRunId = value;
                    this.SendPropertyChanged("SampleRunId");
                    this.OnSampleRunIdChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 1000,  RangeBoundaryType.Inclusive)]
        [NotNullValidator()]
        public string SampleUid
        {
            get
            {
                return this._SampleUid;
            }
            set
            {
                if (this._SampleUid != value)
                {
                    this.OnSampleUidChanging(value);
                    this.SendPropertyChanging("SampleUid");
                    this._SampleUid = value;
                    this.SendPropertyChanged("SampleUid");
                    this.OnSampleUidChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 1000,  RangeBoundaryType.Inclusive)]
        public string FeatureUid
        {
            get
            {
                return this._FeatureUid;
            }
            set
            {
                if (this._FeatureUid != value)
                {
                    this.OnFeatureUidChanging(value);
                    this.SendPropertyChanging("FeatureUid");
                    this._FeatureUid = value;
                    this.SendPropertyChanged("FeatureUid");
                    this.OnFeatureUidChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 200,  RangeBoundaryType.Inclusive)]
        public string Language
        {
            get
            {
                return this._Language;
            }
            set
            {
                if (this._Language != value)
                {
                    this.OnLanguageChanging(value);
                    this.SendPropertyChanging("Language");
                    this._Language = value;
                    this.SendPropertyChanged("Language");
                    this.OnLanguageChanged();
                }
            }
        }

        public string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                if (this._Code != value)
                {
                    this.OnCodeChanging(value);
                    this.SendPropertyChanging("Code");
                    this._Code = value;
                    this.SendPropertyChanged("Code");
                    this.OnCodeChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 400,  RangeBoundaryType.Inclusive)]
        public string EntryPoint
        {
            get
            {
                return this._EntryPoint;
            }
            set
            {
                if (this._EntryPoint != value)
                {
                    this.OnEntryPointChanging(value);
                    this.SendPropertyChanging("EntryPoint");
                    this._EntryPoint = value;
                    this.SendPropertyChanged("EntryPoint");
                    this.OnEntryPointChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 200,  RangeBoundaryType.Inclusive)]
        public string TargetFramework
        {
            get
            {
                return this._TargetFramework;
            }
            set
            {
                if (this._TargetFramework != value)
                {
                    this.OnTargetFrameworkChanging(value);
                    this.SendPropertyChanging("TargetFramework");
                    this._TargetFramework = value;
                    this.SendPropertyChanged("TargetFramework");
                    this.OnTargetFrameworkChanged();
                }
            }
        }

        public string PackageReferences
        {
            get
            {
                return this._PackageReferences;
            }
            set
            {
                if (this._PackageReferences != value)
                {
                    this.OnPackageReferencesChanging(value);
                    this.SendPropertyChanging("PackageReferences");
                    this._PackageReferences = value;
                    this.SendPropertyChanged("PackageReferences");
                    this.OnPackageReferencesChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 1000,  RangeBoundaryType.Inclusive)]
        public string DerivedFromCodeUid
        {
            get
            {
                return this._DerivedFromCodeUid;
            }
            set
            {
                if (this._DerivedFromCodeUid != value)
                {
                    this.OnDerivedFromCodeUidChanging(value);
                    this.SendPropertyChanging("DerivedFromCodeUid");
                    this._DerivedFromCodeUid = value;
                    this.SendPropertyChanged("DerivedFromCodeUid");
                    this.OnDerivedFromCodeUidChanged();
                }
            }
        }

        public string Tags
        {
            get
            {
                return this._Tags;
            }
            set
            {
                if (this._Tags != value)
                {
                    this.OnTagsChanging(value);
                    this.SendPropertyChanging("Tags");
                    this._Tags = value;
                    this.SendPropertyChanged("Tags");
                    this.OnTagsChanged();
                }
            }
        }


        public virtual SampleRun SampleRun
        {
            get
            {
                return this._SampleRun;
            }
            set
            {
                if (this._SampleRun != value)
                {
                    this.OnSampleRunChanging(value);
                    this.SendPropertyChanging("SampleRun");
                    this._SampleRun = value;
                    this.SendPropertyChanged("SampleRun");
                    this.OnSampleRunChanged();
                }
            }
        }


        public virtual ICollection<SampleApiMemberLink> SampleApiMemberLinks
        {
            get
            {
                return this._SampleApiMemberLinks;
            }
            set
            {
                this._SampleApiMemberLinks = value;
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();
        partial void OnIdChanging(Guid value);

        partial void OnIdChanged();
        partial void OnSampleRunIdChanging(Guid value);

        partial void OnSampleRunIdChanged();
        partial void OnSampleUidChanging(string value);

        partial void OnSampleUidChanged();
        partial void OnFeatureUidChanging(string value);

        partial void OnFeatureUidChanged();
        partial void OnLanguageChanging(string value);

        partial void OnLanguageChanged();
        partial void OnCodeChanging(string value);

        partial void OnCodeChanged();
        partial void OnEntryPointChanging(string value);

        partial void OnEntryPointChanged();
        partial void OnTargetFrameworkChanging(string value);

        partial void OnTargetFrameworkChanged();
        partial void OnPackageReferencesChanging(string value);

        partial void OnPackageReferencesChanged();
        partial void OnDerivedFromCodeUidChanging(string value);

        partial void OnDerivedFromCodeUidChanged();
        partial void OnTagsChanging(string value);

        partial void OnTagsChanged();
        partial void OnSampleRunChanging(SampleRun value);

        partial void OnSampleRunChanged();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
