//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 1.25
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.Practices.EnterpriseLibrary.Validation.Validators;

namespace ITCompanionAI.Entities
{
    public partial class DocSection : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private Guid _Id;

        private Guid _DocPageId;

        private string _SemanticUid;

        private string _Heading;

        private int? _Level;

        private string _ContentMarkdown;

        private int? _OrderIndex;

        private int _VersionNumber;

        private Guid _CreatedIngestionRunId;

        private Guid _UpdatedIngestionRunId;

        private Guid? _RemovedIngestionRunId;

        private DateTime _ValidFromUtc;

        private DateTime? _ValidToUtc;

        private bool _IsActive;

        private byte[] _ContentHash;

        private byte[] _SemanticUidHash;

        private ICollection<CodeBlock> _CodeBlocks;

        private DocPage _DocPage;

        private IngestionRun _IngestionRun_CreatedIngestionRunId;

        private IngestionRun _IngestionRun_UpdatedIngestionRunId;

        private IngestionRun _IngestionRun_RemovedIngestionRunId;

        private SemanticIdentity _SemanticIdentity;

        public DocSection()
        {
            this._IsActive = true;
            this._CodeBlocks = new List<CodeBlock>();
            OnCreated();
        }

        [NotNullValidator()]
        public Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging("Id");
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

        [NotNullValidator()]
        public Guid DocPageId
        {
            get
            {
                return this._DocPageId;
            }
            set
            {
                if (this._DocPageId != value)
                {
                    this.OnDocPageIdChanging(value);
                    this.SendPropertyChanging("DocPageId");
                    this._DocPageId = value;
                    this.SendPropertyChanged("DocPageId");
                    this.OnDocPageIdChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 1000,  RangeBoundaryType.Inclusive)]
        [NotNullValidator()]
        public string SemanticUid
        {
            get
            {
                return this._SemanticUid;
            }
            set
            {
                if (this._SemanticUid != value)
                {
                    this.OnSemanticUidChanging(value);
                    this.SendPropertyChanging("SemanticUid");
                    this._SemanticUid = value;
                    this.SendPropertyChanged("SemanticUid");
                    this.OnSemanticUidChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 400,  RangeBoundaryType.Inclusive)]
        public string Heading
        {
            get
            {
                return this._Heading;
            }
            set
            {
                if (this._Heading != value)
                {
                    this.OnHeadingChanging(value);
                    this.SendPropertyChanging("Heading");
                    this._Heading = value;
                    this.SendPropertyChanged("Heading");
                    this.OnHeadingChanged();
                }
            }
        }

        public int? Level
        {
            get
            {
                return this._Level;
            }
            set
            {
                if (this._Level != value)
                {
                    this.OnLevelChanging(value);
                    this.SendPropertyChanging("Level");
                    this._Level = value;
                    this.SendPropertyChanged("Level");
                    this.OnLevelChanged();
                }
            }
        }

        public string ContentMarkdown
        {
            get
            {
                return this._ContentMarkdown;
            }
            set
            {
                if (this._ContentMarkdown != value)
                {
                    this.OnContentMarkdownChanging(value);
                    this.SendPropertyChanging("ContentMarkdown");
                    this._ContentMarkdown = value;
                    this.SendPropertyChanged("ContentMarkdown");
                    this.OnContentMarkdownChanged();
                }
            }
        }

        public int? OrderIndex
        {
            get
            {
                return this._OrderIndex;
            }
            set
            {
                if (this._OrderIndex != value)
                {
                    this.OnOrderIndexChanging(value);
                    this.SendPropertyChanging("OrderIndex");
                    this._OrderIndex = value;
                    this.SendPropertyChanged("OrderIndex");
                    this.OnOrderIndexChanged();
                }
            }
        }

        [NotNullValidator()]
        public int VersionNumber
        {
            get
            {
                return this._VersionNumber;
            }
            set
            {
                if (this._VersionNumber != value)
                {
                    this.OnVersionNumberChanging(value);
                    this.SendPropertyChanging("VersionNumber");
                    this._VersionNumber = value;
                    this.SendPropertyChanged("VersionNumber");
                    this.OnVersionNumberChanged();
                }
            }
        }

        [NotNullValidator()]
        public Guid CreatedIngestionRunId
        {
            get
            {
                return this._CreatedIngestionRunId;
            }
            set
            {
                if (this._CreatedIngestionRunId != value)
                {
                    this.OnCreatedIngestionRunIdChanging(value);
                    this.SendPropertyChanging("CreatedIngestionRunId");
                    this._CreatedIngestionRunId = value;
                    this.SendPropertyChanged("CreatedIngestionRunId");
                    this.OnCreatedIngestionRunIdChanged();
                }
            }
        }

        [NotNullValidator()]
        public Guid UpdatedIngestionRunId
        {
            get
            {
                return this._UpdatedIngestionRunId;
            }
            set
            {
                if (this._UpdatedIngestionRunId != value)
                {
                    this.OnUpdatedIngestionRunIdChanging(value);
                    this.SendPropertyChanging("UpdatedIngestionRunId");
                    this._UpdatedIngestionRunId = value;
                    this.SendPropertyChanged("UpdatedIngestionRunId");
                    this.OnUpdatedIngestionRunIdChanged();
                }
            }
        }

        public Guid? RemovedIngestionRunId
        {
            get
            {
                return this._RemovedIngestionRunId;
            }
            set
            {
                if (this._RemovedIngestionRunId != value)
                {
                    this.OnRemovedIngestionRunIdChanging(value);
                    this.SendPropertyChanging("RemovedIngestionRunId");
                    this._RemovedIngestionRunId = value;
                    this.SendPropertyChanged("RemovedIngestionRunId");
                    this.OnRemovedIngestionRunIdChanged();
                }
            }
        }

        [NotNullValidator()]
        public DateTime ValidFromUtc
        {
            get
            {
                return this._ValidFromUtc;
            }
            set
            {
                if (this._ValidFromUtc != value)
                {
                    this.OnValidFromUtcChanging(value);
                    this.SendPropertyChanging("ValidFromUtc");
                    this._ValidFromUtc = value;
                    this.SendPropertyChanged("ValidFromUtc");
                    this.OnValidFromUtcChanged();
                }
            }
        }

        public DateTime? ValidToUtc
        {
            get
            {
                return this._ValidToUtc;
            }
            set
            {
                if (this._ValidToUtc != value)
                {
                    this.OnValidToUtcChanging(value);
                    this.SendPropertyChanging("ValidToUtc");
                    this._ValidToUtc = value;
                    this.SendPropertyChanged("ValidToUtc");
                    this.OnValidToUtcChanged();
                }
            }
        }

        [NotNullValidator()]
        public bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                if (this._IsActive != value)
                {
                    this.OnIsActiveChanging(value);
                    this.SendPropertyChanging("IsActive");
                    this._IsActive = value;
                    this.SendPropertyChanged("IsActive");
                    this.OnIsActiveChanged();
                }
            }
        }

        public byte[] ContentHash
        {
            get
            {
                return this._ContentHash;
            }
            set
            {
                if (this._ContentHash != value)
                {
                    this.OnContentHashChanging(value);
                    this.SendPropertyChanging("ContentHash");
                    this._ContentHash = value;
                    this.SendPropertyChanged("ContentHash");
                    this.OnContentHashChanged();
                }
            }
        }

        public byte[] SemanticUidHash
        {
            get
            {
                return this._SemanticUidHash;
            }
            set
            {
                if (this._SemanticUidHash != value)
                {
                    this.OnSemanticUidHashChanging(value);
                    this.SendPropertyChanging("SemanticUidHash");
                    this._SemanticUidHash = value;
                    this.SendPropertyChanged("SemanticUidHash");
                    this.OnSemanticUidHashChanged();
                }
            }
        }


        public virtual ICollection<CodeBlock> CodeBlocks
        {
            get
            {
                return this._CodeBlocks;
            }
            set
            {
                this._CodeBlocks = value;
            }
        }


        public virtual DocPage DocPage
        {
            get
            {
                return this._DocPage;
            }
            set
            {
                if (this._DocPage != value)
                {
                    this.OnDocPageChanging(value);
                    this.SendPropertyChanging("DocPage");
                    this._DocPage = value;
                    this.SendPropertyChanged("DocPage");
                    this.OnDocPageChanged();
                }
            }
        }


        public virtual IngestionRun IngestionRun_CreatedIngestionRunId
        {
            get
            {
                return this._IngestionRun_CreatedIngestionRunId;
            }
            set
            {
                if (this._IngestionRun_CreatedIngestionRunId != value)
                {
                    this.OnIngestionRun_CreatedIngestionRunIdChanging(value);
                    this.SendPropertyChanging("IngestionRun_CreatedIngestionRunId");
                    this._IngestionRun_CreatedIngestionRunId = value;
                    this.SendPropertyChanged("IngestionRun_CreatedIngestionRunId");
                    this.OnIngestionRun_CreatedIngestionRunIdChanged();
                }
            }
        }


        public virtual IngestionRun IngestionRun_UpdatedIngestionRunId
        {
            get
            {
                return this._IngestionRun_UpdatedIngestionRunId;
            }
            set
            {
                if (this._IngestionRun_UpdatedIngestionRunId != value)
                {
                    this.OnIngestionRun_UpdatedIngestionRunIdChanging(value);
                    this.SendPropertyChanging("IngestionRun_UpdatedIngestionRunId");
                    this._IngestionRun_UpdatedIngestionRunId = value;
                    this.SendPropertyChanged("IngestionRun_UpdatedIngestionRunId");
                    this.OnIngestionRun_UpdatedIngestionRunIdChanged();
                }
            }
        }


        public virtual IngestionRun IngestionRun_RemovedIngestionRunId
        {
            get
            {
                return this._IngestionRun_RemovedIngestionRunId;
            }
            set
            {
                if (this._IngestionRun_RemovedIngestionRunId != value)
                {
                    this.OnIngestionRun_RemovedIngestionRunIdChanging(value);
                    this.SendPropertyChanging("IngestionRun_RemovedIngestionRunId");
                    this._IngestionRun_RemovedIngestionRunId = value;
                    this.SendPropertyChanged("IngestionRun_RemovedIngestionRunId");
                    this.OnIngestionRun_RemovedIngestionRunIdChanged();
                }
            }
        }


        public virtual SemanticIdentity SemanticIdentity
        {
            get
            {
                return this._SemanticIdentity;
            }
            set
            {
                if (this._SemanticIdentity != value)
                {
                    this.OnSemanticIdentityChanging(value);
                    this.SendPropertyChanging("SemanticIdentity");
                    this._SemanticIdentity = value;
                    this.SendPropertyChanged("SemanticIdentity");
                    this.OnSemanticIdentityChanged();
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();
        partial void OnIdChanging(Guid value);

        partial void OnIdChanged();
        partial void OnDocPageIdChanging(Guid value);

        partial void OnDocPageIdChanged();
        partial void OnSemanticUidChanging(string value);

        partial void OnSemanticUidChanged();
        partial void OnHeadingChanging(string value);

        partial void OnHeadingChanged();
        partial void OnLevelChanging(int? value);

        partial void OnLevelChanged();
        partial void OnContentMarkdownChanging(string value);

        partial void OnContentMarkdownChanged();
        partial void OnOrderIndexChanging(int? value);

        partial void OnOrderIndexChanged();
        partial void OnVersionNumberChanging(int value);

        partial void OnVersionNumberChanged();
        partial void OnCreatedIngestionRunIdChanging(Guid value);

        partial void OnCreatedIngestionRunIdChanged();
        partial void OnUpdatedIngestionRunIdChanging(Guid value);

        partial void OnUpdatedIngestionRunIdChanged();
        partial void OnRemovedIngestionRunIdChanging(Guid? value);

        partial void OnRemovedIngestionRunIdChanged();
        partial void OnValidFromUtcChanging(DateTime value);

        partial void OnValidFromUtcChanged();
        partial void OnValidToUtcChanging(DateTime? value);

        partial void OnValidToUtcChanged();
        partial void OnIsActiveChanging(bool value);

        partial void OnIsActiveChanged();
        partial void OnContentHashChanging(byte[] value);

        partial void OnContentHashChanged();
        partial void OnSemanticUidHashChanging(byte[] value);

        partial void OnSemanticUidHashChanged();
        partial void OnDocPageChanging(DocPage value);

        partial void OnDocPageChanged();
        partial void OnIngestionRun_CreatedIngestionRunIdChanging(IngestionRun value);

        partial void OnIngestionRun_CreatedIngestionRunIdChanged();
        partial void OnIngestionRun_UpdatedIngestionRunIdChanging(IngestionRun value);

        partial void OnIngestionRun_UpdatedIngestionRunIdChanged();
        partial void OnIngestionRun_RemovedIngestionRunIdChanging(IngestionRun value);

        partial void OnIngestionRun_RemovedIngestionRunIdChanged();
        partial void OnSemanticIdentityChanging(SemanticIdentity value);

        partial void OnSemanticIdentityChanged();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
