//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 1.25
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.Practices.EnterpriseLibrary.Validation.Validators;

namespace ITCompanionAI.Entities
{
    public partial class CodeBlock : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private Guid _Id;

        private Guid _DocSectionId;

        private string _SemanticUid;

        private string _Language;

        private string _Content;

        private string _DeclaredPackages;

        private string _Tags;

        private string _InlineComments;

        private int _VersionNumber;

        private Guid _CreatedIngestionRunId;

        private Guid _UpdatedIngestionRunId;

        private Guid? _RemovedIngestionRunId;

        private DateTime _ValidFromUtc;

        private DateTime? _ValidToUtc;

        private bool _IsActive;

        private byte[] _ContentHash;

        private DocSection _DocSection;

        private IngestionRun _IngestionRun_CreatedIngestionRunId;

        private IngestionRun _IngestionRun_UpdatedIngestionRunId;

        private IngestionRun _IngestionRun_RemovedIngestionRunId;

        public CodeBlock()
        {
            this._IsActive = true;
            OnCreated();
        }

        [NotNullValidator()]
        public Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging("Id");
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

        [NotNullValidator()]
        public Guid DocSectionId
        {
            get
            {
                return this._DocSectionId;
            }
            set
            {
                if (this._DocSectionId != value)
                {
                    this.OnDocSectionIdChanging(value);
                    this.SendPropertyChanging("DocSectionId");
                    this._DocSectionId = value;
                    this.SendPropertyChanged("DocSectionId");
                    this.OnDocSectionIdChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 1000,  RangeBoundaryType.Inclusive)]
        public string SemanticUid
        {
            get
            {
                return this._SemanticUid;
            }
            set
            {
                if (this._SemanticUid != value)
                {
                    this.OnSemanticUidChanging(value);
                    this.SendPropertyChanging("SemanticUid");
                    this._SemanticUid = value;
                    this.SendPropertyChanged("SemanticUid");
                    this.OnSemanticUidChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 200,  RangeBoundaryType.Inclusive)]
        public string Language
        {
            get
            {
                return this._Language;
            }
            set
            {
                if (this._Language != value)
                {
                    this.OnLanguageChanging(value);
                    this.SendPropertyChanging("Language");
                    this._Language = value;
                    this.SendPropertyChanged("Language");
                    this.OnLanguageChanged();
                }
            }
        }

        public string Content
        {
            get
            {
                return this._Content;
            }
            set
            {
                if (this._Content != value)
                {
                    this.OnContentChanging(value);
                    this.SendPropertyChanging("Content");
                    this._Content = value;
                    this.SendPropertyChanged("Content");
                    this.OnContentChanged();
                }
            }
        }

        public string DeclaredPackages
        {
            get
            {
                return this._DeclaredPackages;
            }
            set
            {
                if (this._DeclaredPackages != value)
                {
                    this.OnDeclaredPackagesChanging(value);
                    this.SendPropertyChanging("DeclaredPackages");
                    this._DeclaredPackages = value;
                    this.SendPropertyChanged("DeclaredPackages");
                    this.OnDeclaredPackagesChanged();
                }
            }
        }

        public string Tags
        {
            get
            {
                return this._Tags;
            }
            set
            {
                if (this._Tags != value)
                {
                    this.OnTagsChanging(value);
                    this.SendPropertyChanging("Tags");
                    this._Tags = value;
                    this.SendPropertyChanged("Tags");
                    this.OnTagsChanged();
                }
            }
        }

        public string InlineComments
        {
            get
            {
                return this._InlineComments;
            }
            set
            {
                if (this._InlineComments != value)
                {
                    this.OnInlineCommentsChanging(value);
                    this.SendPropertyChanging("InlineComments");
                    this._InlineComments = value;
                    this.SendPropertyChanged("InlineComments");
                    this.OnInlineCommentsChanged();
                }
            }
        }

        [NotNullValidator()]
        public int VersionNumber
        {
            get
            {
                return this._VersionNumber;
            }
            set
            {
                if (this._VersionNumber != value)
                {
                    this.OnVersionNumberChanging(value);
                    this.SendPropertyChanging("VersionNumber");
                    this._VersionNumber = value;
                    this.SendPropertyChanged("VersionNumber");
                    this.OnVersionNumberChanged();
                }
            }
        }

        [NotNullValidator()]
        public Guid CreatedIngestionRunId
        {
            get
            {
                return this._CreatedIngestionRunId;
            }
            set
            {
                if (this._CreatedIngestionRunId != value)
                {
                    this.OnCreatedIngestionRunIdChanging(value);
                    this.SendPropertyChanging("CreatedIngestionRunId");
                    this._CreatedIngestionRunId = value;
                    this.SendPropertyChanged("CreatedIngestionRunId");
                    this.OnCreatedIngestionRunIdChanged();
                }
            }
        }

        [NotNullValidator()]
        public Guid UpdatedIngestionRunId
        {
            get
            {
                return this._UpdatedIngestionRunId;
            }
            set
            {
                if (this._UpdatedIngestionRunId != value)
                {
                    this.OnUpdatedIngestionRunIdChanging(value);
                    this.SendPropertyChanging("UpdatedIngestionRunId");
                    this._UpdatedIngestionRunId = value;
                    this.SendPropertyChanged("UpdatedIngestionRunId");
                    this.OnUpdatedIngestionRunIdChanged();
                }
            }
        }

        public Guid? RemovedIngestionRunId
        {
            get
            {
                return this._RemovedIngestionRunId;
            }
            set
            {
                if (this._RemovedIngestionRunId != value)
                {
                    this.OnRemovedIngestionRunIdChanging(value);
                    this.SendPropertyChanging("RemovedIngestionRunId");
                    this._RemovedIngestionRunId = value;
                    this.SendPropertyChanged("RemovedIngestionRunId");
                    this.OnRemovedIngestionRunIdChanged();
                }
            }
        }

        [NotNullValidator()]
        public DateTime ValidFromUtc
        {
            get
            {
                return this._ValidFromUtc;
            }
            set
            {
                if (this._ValidFromUtc != value)
                {
                    this.OnValidFromUtcChanging(value);
                    this.SendPropertyChanging("ValidFromUtc");
                    this._ValidFromUtc = value;
                    this.SendPropertyChanged("ValidFromUtc");
                    this.OnValidFromUtcChanged();
                }
            }
        }

        public DateTime? ValidToUtc
        {
            get
            {
                return this._ValidToUtc;
            }
            set
            {
                if (this._ValidToUtc != value)
                {
                    this.OnValidToUtcChanging(value);
                    this.SendPropertyChanging("ValidToUtc");
                    this._ValidToUtc = value;
                    this.SendPropertyChanged("ValidToUtc");
                    this.OnValidToUtcChanged();
                }
            }
        }

        [NotNullValidator()]
        public bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                if (this._IsActive != value)
                {
                    this.OnIsActiveChanging(value);
                    this.SendPropertyChanging("IsActive");
                    this._IsActive = value;
                    this.SendPropertyChanged("IsActive");
                    this.OnIsActiveChanged();
                }
            }
        }

        public byte[] ContentHash
        {
            get
            {
                return this._ContentHash;
            }
            set
            {
                if (this._ContentHash != value)
                {
                    this.OnContentHashChanging(value);
                    this.SendPropertyChanging("ContentHash");
                    this._ContentHash = value;
                    this.SendPropertyChanged("ContentHash");
                    this.OnContentHashChanged();
                }
            }
        }


        public virtual DocSection DocSection
        {
            get
            {
                return this._DocSection;
            }
            set
            {
                if (this._DocSection != value)
                {
                    this.OnDocSectionChanging(value);
                    this.SendPropertyChanging("DocSection");
                    this._DocSection = value;
                    this.SendPropertyChanged("DocSection");
                    this.OnDocSectionChanged();
                }
            }
        }


        public virtual IngestionRun IngestionRun_CreatedIngestionRunId
        {
            get
            {
                return this._IngestionRun_CreatedIngestionRunId;
            }
            set
            {
                if (this._IngestionRun_CreatedIngestionRunId != value)
                {
                    this.OnIngestionRun_CreatedIngestionRunIdChanging(value);
                    this.SendPropertyChanging("IngestionRun_CreatedIngestionRunId");
                    this._IngestionRun_CreatedIngestionRunId = value;
                    this.SendPropertyChanged("IngestionRun_CreatedIngestionRunId");
                    this.OnIngestionRun_CreatedIngestionRunIdChanged();
                }
            }
        }


        public virtual IngestionRun IngestionRun_UpdatedIngestionRunId
        {
            get
            {
                return this._IngestionRun_UpdatedIngestionRunId;
            }
            set
            {
                if (this._IngestionRun_UpdatedIngestionRunId != value)
                {
                    this.OnIngestionRun_UpdatedIngestionRunIdChanging(value);
                    this.SendPropertyChanging("IngestionRun_UpdatedIngestionRunId");
                    this._IngestionRun_UpdatedIngestionRunId = value;
                    this.SendPropertyChanged("IngestionRun_UpdatedIngestionRunId");
                    this.OnIngestionRun_UpdatedIngestionRunIdChanged();
                }
            }
        }


        public virtual IngestionRun IngestionRun_RemovedIngestionRunId
        {
            get
            {
                return this._IngestionRun_RemovedIngestionRunId;
            }
            set
            {
                if (this._IngestionRun_RemovedIngestionRunId != value)
                {
                    this.OnIngestionRun_RemovedIngestionRunIdChanging(value);
                    this.SendPropertyChanging("IngestionRun_RemovedIngestionRunId");
                    this._IngestionRun_RemovedIngestionRunId = value;
                    this.SendPropertyChanged("IngestionRun_RemovedIngestionRunId");
                    this.OnIngestionRun_RemovedIngestionRunIdChanged();
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();
        partial void OnIdChanging(Guid value);

        partial void OnIdChanged();
        partial void OnDocSectionIdChanging(Guid value);

        partial void OnDocSectionIdChanged();
        partial void OnSemanticUidChanging(string value);

        partial void OnSemanticUidChanged();
        partial void OnLanguageChanging(string value);

        partial void OnLanguageChanged();
        partial void OnContentChanging(string value);

        partial void OnContentChanged();
        partial void OnDeclaredPackagesChanging(string value);

        partial void OnDeclaredPackagesChanged();
        partial void OnTagsChanging(string value);

        partial void OnTagsChanged();
        partial void OnInlineCommentsChanging(string value);

        partial void OnInlineCommentsChanged();
        partial void OnVersionNumberChanging(int value);

        partial void OnVersionNumberChanged();
        partial void OnCreatedIngestionRunIdChanging(Guid value);

        partial void OnCreatedIngestionRunIdChanged();
        partial void OnUpdatedIngestionRunIdChanging(Guid value);

        partial void OnUpdatedIngestionRunIdChanged();
        partial void OnRemovedIngestionRunIdChanging(Guid? value);

        partial void OnRemovedIngestionRunIdChanged();
        partial void OnValidFromUtcChanging(DateTime value);

        partial void OnValidFromUtcChanged();
        partial void OnValidToUtcChanging(DateTime? value);

        partial void OnValidToUtcChanged();
        partial void OnIsActiveChanging(bool value);

        partial void OnIsActiveChanged();
        partial void OnContentHashChanging(byte[] value);

        partial void OnContentHashChanged();
        partial void OnDocSectionChanging(DocSection value);

        partial void OnDocSectionChanged();
        partial void OnIngestionRun_CreatedIngestionRunIdChanging(IngestionRun value);

        partial void OnIngestionRun_CreatedIngestionRunIdChanged();
        partial void OnIngestionRun_UpdatedIngestionRunIdChanging(IngestionRun value);

        partial void OnIngestionRun_UpdatedIngestionRunIdChanged();
        partial void OnIngestionRun_RemovedIngestionRunIdChanging(IngestionRun value);

        partial void OnIngestionRun_RemovedIngestionRunIdChanged();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
