//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 1.25
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.Practices.EnterpriseLibrary.Validation.Validators;

namespace ITCompanionAI.Entities
{
    public partial class SemanticIdentity : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private string _Uid;

        private byte[] _UidHash;

        private string _Kind;

        private DateTime _CreatedUtc;

        private string _Notes;

        private ICollection<ApiFeature> _ApiFeatures;

        private ICollection<DocPage> _DocPages;

        private ICollection<DocSection> _DocSections;

        public SemanticIdentity()
        {
            this._ApiFeatures = new List<ApiFeature>();
            this._DocPages = new List<DocPage>();
            this._DocSections = new List<DocSection>();
            OnCreated();
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 1000,  RangeBoundaryType.Inclusive)]
        [NotNullValidator()]
        public string Uid
        {
            get
            {
                return this._Uid;
            }
            set
            {
                if (this._Uid != value)
                {
                    this.OnUidChanging(value);
                    this.SendPropertyChanging("Uid");
                    this._Uid = value;
                    this.SendPropertyChanged("Uid");
                    this.OnUidChanged();
                }
            }
        }

        [NotNullValidator()]
        public byte[] UidHash
        {
            get
            {
                return this._UidHash;
            }
            set
            {
                if (this._UidHash != value)
                {
                    this.OnUidHashChanging(value);
                    this.SendPropertyChanging("UidHash");
                    this._UidHash = value;
                    this.SendPropertyChanged("UidHash");
                    this.OnUidHashChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 50,  RangeBoundaryType.Inclusive)]
        [NotNullValidator()]
        public string Kind
        {
            get
            {
                return this._Kind;
            }
            set
            {
                if (this._Kind != value)
                {
                    this.OnKindChanging(value);
                    this.SendPropertyChanging("Kind");
                    this._Kind = value;
                    this.SendPropertyChanged("Kind");
                    this.OnKindChanged();
                }
            }
        }

        [NotNullValidator()]
        public DateTime CreatedUtc
        {
            get
            {
                return this._CreatedUtc;
            }
            set
            {
                if (this._CreatedUtc != value)
                {
                    this.OnCreatedUtcChanging(value);
                    this.SendPropertyChanging("CreatedUtc");
                    this._CreatedUtc = value;
                    this.SendPropertyChanged("CreatedUtc");
                    this.OnCreatedUtcChanged();
                }
            }
        }

        public string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                if (this._Notes != value)
                {
                    this.OnNotesChanging(value);
                    this.SendPropertyChanging("Notes");
                    this._Notes = value;
                    this.SendPropertyChanged("Notes");
                    this.OnNotesChanged();
                }
            }
        }


        public virtual ICollection<ApiFeature> ApiFeatures
        {
            get
            {
                return this._ApiFeatures;
            }
            set
            {
                this._ApiFeatures = value;
            }
        }


        public virtual ICollection<DocPage> DocPages
        {
            get
            {
                return this._DocPages;
            }
            set
            {
                this._DocPages = value;
            }
        }


        public virtual ICollection<DocSection> DocSections
        {
            get
            {
                return this._DocSections;
            }
            set
            {
                this._DocSections = value;
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();
        partial void OnUidChanging(string value);

        partial void OnUidChanged();
        partial void OnUidHashChanging(byte[] value);

        partial void OnUidHashChanged();
        partial void OnKindChanging(string value);

        partial void OnKindChanged();
        partial void OnCreatedUtcChanging(DateTime value);

        partial void OnCreatedUtcChanged();
        partial void OnNotesChanging(string value);

        partial void OnNotesChanged();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
