//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 1.25
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.Practices.EnterpriseLibrary.Validation.Validators;

namespace ITCompanionAI.Entities
{
    public partial class ApiMemberDiff : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private Guid _Id;

        private Guid _SnapshotDiffId;

        private string _MemberUid;

        private string _ChangeKind;

        private string _OldSignature;

        private string _NewSignature;

        private bool? _Breaking;

        private string _DetailJson;

        private SnapshotDiff _SnapshotDiff;

        public ApiMemberDiff()
        {
            OnCreated();
        }

        [NotNullValidator()]
        public Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging("Id");
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

        [NotNullValidator()]
        public Guid SnapshotDiffId
        {
            get
            {
                return this._SnapshotDiffId;
            }
            set
            {
                if (this._SnapshotDiffId != value)
                {
                    this.OnSnapshotDiffIdChanging(value);
                    this.SendPropertyChanging("SnapshotDiffId");
                    this._SnapshotDiffId = value;
                    this.SendPropertyChanged("SnapshotDiffId");
                    this.OnSnapshotDiffIdChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 1000,  RangeBoundaryType.Inclusive)]
        [NotNullValidator()]
        public string MemberUid
        {
            get
            {
                return this._MemberUid;
            }
            set
            {
                if (this._MemberUid != value)
                {
                    this.OnMemberUidChanging(value);
                    this.SendPropertyChanging("MemberUid");
                    this._MemberUid = value;
                    this.SendPropertyChanged("MemberUid");
                    this.OnMemberUidChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 200,  RangeBoundaryType.Inclusive)]
        public string ChangeKind
        {
            get
            {
                return this._ChangeKind;
            }
            set
            {
                if (this._ChangeKind != value)
                {
                    this.OnChangeKindChanging(value);
                    this.SendPropertyChanging("ChangeKind");
                    this._ChangeKind = value;
                    this.SendPropertyChanged("ChangeKind");
                    this.OnChangeKindChanged();
                }
            }
        }

        public string OldSignature
        {
            get
            {
                return this._OldSignature;
            }
            set
            {
                if (this._OldSignature != value)
                {
                    this.OnOldSignatureChanging(value);
                    this.SendPropertyChanging("OldSignature");
                    this._OldSignature = value;
                    this.SendPropertyChanged("OldSignature");
                    this.OnOldSignatureChanged();
                }
            }
        }

        public string NewSignature
        {
            get
            {
                return this._NewSignature;
            }
            set
            {
                if (this._NewSignature != value)
                {
                    this.OnNewSignatureChanging(value);
                    this.SendPropertyChanging("NewSignature");
                    this._NewSignature = value;
                    this.SendPropertyChanged("NewSignature");
                    this.OnNewSignatureChanged();
                }
            }
        }

        public bool? Breaking
        {
            get
            {
                return this._Breaking;
            }
            set
            {
                if (this._Breaking != value)
                {
                    this.OnBreakingChanging(value);
                    this.SendPropertyChanging("Breaking");
                    this._Breaking = value;
                    this.SendPropertyChanged("Breaking");
                    this.OnBreakingChanged();
                }
            }
        }

        public string DetailJson
        {
            get
            {
                return this._DetailJson;
            }
            set
            {
                if (this._DetailJson != value)
                {
                    this.OnDetailJsonChanging(value);
                    this.SendPropertyChanging("DetailJson");
                    this._DetailJson = value;
                    this.SendPropertyChanged("DetailJson");
                    this.OnDetailJsonChanged();
                }
            }
        }


        public virtual SnapshotDiff SnapshotDiff
        {
            get
            {
                return this._SnapshotDiff;
            }
            set
            {
                if (this._SnapshotDiff != value)
                {
                    this.OnSnapshotDiffChanging(value);
                    this.SendPropertyChanging("SnapshotDiff");
                    this._SnapshotDiff = value;
                    this.SendPropertyChanged("SnapshotDiff");
                    this.OnSnapshotDiffChanged();
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();
        partial void OnIdChanging(Guid value);

        partial void OnIdChanged();
        partial void OnSnapshotDiffIdChanging(Guid value);

        partial void OnSnapshotDiffIdChanged();
        partial void OnMemberUidChanging(string value);

        partial void OnMemberUidChanged();
        partial void OnChangeKindChanging(string value);

        partial void OnChangeKindChanged();
        partial void OnOldSignatureChanging(string value);

        partial void OnOldSignatureChanged();
        partial void OnNewSignatureChanging(string value);

        partial void OnNewSignatureChanged();
        partial void OnBreakingChanging(bool? value);

        partial void OnBreakingChanged();
        partial void OnDetailJsonChanging(string value);

        partial void OnDetailJsonChanged();
        partial void OnSnapshotDiffChanging(SnapshotDiff value);

        partial void OnSnapshotDiffChanged();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
