//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 1.25
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.Practices.EnterpriseLibrary.Validation.Validators;

namespace ITCompanionAI.Entities
{
    public partial class FeatureMemberLink : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private Guid _Id;

        private Guid _FeatureId;

        private string _MemberUid;

        private string _Role;

        private ApiFeature _ApiFeature;

        public FeatureMemberLink()
        {
            OnCreated();
        }

        [NotNullValidator()]
        public Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging("Id");
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

        [NotNullValidator()]
        public Guid FeatureId
        {
            get
            {
                return this._FeatureId;
            }
            set
            {
                if (this._FeatureId != value)
                {
                    this.OnFeatureIdChanging(value);
                    this.SendPropertyChanging("FeatureId");
                    this._FeatureId = value;
                    this.SendPropertyChanged("FeatureId");
                    this.OnFeatureIdChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 1000,  RangeBoundaryType.Inclusive)]
        [NotNullValidator()]
        public string MemberUid
        {
            get
            {
                return this._MemberUid;
            }
            set
            {
                if (this._MemberUid != value)
                {
                    this.OnMemberUidChanging(value);
                    this.SendPropertyChanging("MemberUid");
                    this._MemberUid = value;
                    this.SendPropertyChanged("MemberUid");
                    this.OnMemberUidChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 50,  RangeBoundaryType.Inclusive)]
        public string Role
        {
            get
            {
                return this._Role;
            }
            set
            {
                if (this._Role != value)
                {
                    this.OnRoleChanging(value);
                    this.SendPropertyChanging("Role");
                    this._Role = value;
                    this.SendPropertyChanged("Role");
                    this.OnRoleChanged();
                }
            }
        }


        public virtual ApiFeature ApiFeature
        {
            get
            {
                return this._ApiFeature;
            }
            set
            {
                if (this._ApiFeature != value)
                {
                    this.OnApiFeatureChanging(value);
                    this.SendPropertyChanging("ApiFeature");
                    this._ApiFeature = value;
                    this.SendPropertyChanged("ApiFeature");
                    this.OnApiFeatureChanged();
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();
        partial void OnIdChanging(Guid value);

        partial void OnIdChanged();
        partial void OnFeatureIdChanging(Guid value);

        partial void OnFeatureIdChanged();
        partial void OnMemberUidChanging(string value);

        partial void OnMemberUidChanged();
        partial void OnRoleChanging(string value);

        partial void OnRoleChanged();
        partial void OnApiFeatureChanging(ApiFeature value);

        partial void OnApiFeatureChanged();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
