//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 1.25
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.Practices.EnterpriseLibrary.Validation.Validators;

namespace ITCompanionAI.Entities
{
    public partial class ExecutionResult : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private Guid _Id;

        private Guid _ExecutionRunId;

        private string _SampleUid;

        private string _Status;

        private string _BuildLog;

        private string _RunLog;

        private string _ExceptionJson;

        private int? _DurationMs;

        private ExecutionRun _ExecutionRun;

        public ExecutionResult()
        {
            OnCreated();
        }

        [NotNullValidator()]
        public Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging("Id");
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

        [NotNullValidator()]
        public Guid ExecutionRunId
        {
            get
            {
                return this._ExecutionRunId;
            }
            set
            {
                if (this._ExecutionRunId != value)
                {
                    this.OnExecutionRunIdChanging(value);
                    this.SendPropertyChanging("ExecutionRunId");
                    this._ExecutionRunId = value;
                    this.SendPropertyChanged("ExecutionRunId");
                    this.OnExecutionRunIdChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 1000,  RangeBoundaryType.Inclusive)]
        [NotNullValidator()]
        public string SampleUid
        {
            get
            {
                return this._SampleUid;
            }
            set
            {
                if (this._SampleUid != value)
                {
                    this.OnSampleUidChanging(value);
                    this.SendPropertyChanging("SampleUid");
                    this._SampleUid = value;
                    this.SendPropertyChanged("SampleUid");
                    this.OnSampleUidChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 100,  RangeBoundaryType.Inclusive)]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                if (this._Status != value)
                {
                    this.OnStatusChanging(value);
                    this.SendPropertyChanging("Status");
                    this._Status = value;
                    this.SendPropertyChanged("Status");
                    this.OnStatusChanged();
                }
            }
        }

        public string BuildLog
        {
            get
            {
                return this._BuildLog;
            }
            set
            {
                if (this._BuildLog != value)
                {
                    this.OnBuildLogChanging(value);
                    this.SendPropertyChanging("BuildLog");
                    this._BuildLog = value;
                    this.SendPropertyChanged("BuildLog");
                    this.OnBuildLogChanged();
                }
            }
        }

        public string RunLog
        {
            get
            {
                return this._RunLog;
            }
            set
            {
                if (this._RunLog != value)
                {
                    this.OnRunLogChanging(value);
                    this.SendPropertyChanging("RunLog");
                    this._RunLog = value;
                    this.SendPropertyChanged("RunLog");
                    this.OnRunLogChanged();
                }
            }
        }

        public string ExceptionJson
        {
            get
            {
                return this._ExceptionJson;
            }
            set
            {
                if (this._ExceptionJson != value)
                {
                    this.OnExceptionJsonChanging(value);
                    this.SendPropertyChanging("ExceptionJson");
                    this._ExceptionJson = value;
                    this.SendPropertyChanged("ExceptionJson");
                    this.OnExceptionJsonChanged();
                }
            }
        }

        public int? DurationMs
        {
            get
            {
                return this._DurationMs;
            }
            set
            {
                if (this._DurationMs != value)
                {
                    this.OnDurationMsChanging(value);
                    this.SendPropertyChanging("DurationMs");
                    this._DurationMs = value;
                    this.SendPropertyChanged("DurationMs");
                    this.OnDurationMsChanged();
                }
            }
        }


        public virtual ExecutionRun ExecutionRun
        {
            get
            {
                return this._ExecutionRun;
            }
            set
            {
                if (this._ExecutionRun != value)
                {
                    this.OnExecutionRunChanging(value);
                    this.SendPropertyChanging("ExecutionRun");
                    this._ExecutionRun = value;
                    this.SendPropertyChanged("ExecutionRun");
                    this.OnExecutionRunChanged();
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();
        partial void OnIdChanging(Guid value);

        partial void OnIdChanged();
        partial void OnExecutionRunIdChanging(Guid value);

        partial void OnExecutionRunIdChanged();
        partial void OnSampleUidChanging(string value);

        partial void OnSampleUidChanged();
        partial void OnStatusChanging(string value);

        partial void OnStatusChanged();
        partial void OnBuildLogChanging(string value);

        partial void OnBuildLogChanged();
        partial void OnRunLogChanging(string value);

        partial void OnRunLogChanged();
        partial void OnExceptionJsonChanging(string value);

        partial void OnExceptionJsonChanged();
        partial void OnDurationMsChanging(int? value);

        partial void OnDurationMsChanged();
        partial void OnExecutionRunChanging(ExecutionRun value);

        partial void OnExecutionRunChanged();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
