//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 1.25
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.Practices.EnterpriseLibrary.Validation.Validators;

namespace ITCompanionAI.Entities
{
    public partial class FeatureDocLink : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private Guid _Id;

        private Guid _FeatureId;

        private string _DocUid;

        private string _SectionUid;

        private ApiFeature _ApiFeature;

        public FeatureDocLink()
        {
            OnCreated();
        }

        [NotNullValidator()]
        public Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging("Id");
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

        [NotNullValidator()]
        public Guid FeatureId
        {
            get
            {
                return this._FeatureId;
            }
            set
            {
                if (this._FeatureId != value)
                {
                    this.OnFeatureIdChanging(value);
                    this.SendPropertyChanging("FeatureId");
                    this._FeatureId = value;
                    this.SendPropertyChanged("FeatureId");
                    this.OnFeatureIdChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 1000,  RangeBoundaryType.Inclusive)]
        [NotNullValidator()]
        public string DocUid
        {
            get
            {
                return this._DocUid;
            }
            set
            {
                if (this._DocUid != value)
                {
                    this.OnDocUidChanging(value);
                    this.SendPropertyChanging("DocUid");
                    this._DocUid = value;
                    this.SendPropertyChanged("DocUid");
                    this.OnDocUidChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 1000,  RangeBoundaryType.Inclusive)]
        public string SectionUid
        {
            get
            {
                return this._SectionUid;
            }
            set
            {
                if (this._SectionUid != value)
                {
                    this.OnSectionUidChanging(value);
                    this.SendPropertyChanging("SectionUid");
                    this._SectionUid = value;
                    this.SendPropertyChanged("SectionUid");
                    this.OnSectionUidChanged();
                }
            }
        }


        public virtual ApiFeature ApiFeature
        {
            get
            {
                return this._ApiFeature;
            }
            set
            {
                if (this._ApiFeature != value)
                {
                    this.OnApiFeatureChanging(value);
                    this.SendPropertyChanging("ApiFeature");
                    this._ApiFeature = value;
                    this.SendPropertyChanged("ApiFeature");
                    this.OnApiFeatureChanged();
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();
        partial void OnIdChanging(Guid value);

        partial void OnIdChanged();
        partial void OnFeatureIdChanging(Guid value);

        partial void OnFeatureIdChanged();
        partial void OnDocUidChanging(string value);

        partial void OnDocUidChanged();
        partial void OnSectionUidChanging(string value);

        partial void OnSectionUidChanged();
        partial void OnApiFeatureChanging(ApiFeature value);

        partial void OnApiFeatureChanged();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
