//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 1.25
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.Practices.EnterpriseLibrary.Validation.Validators;

namespace ITCompanionAI.Entities
{
    public partial class SourceSnapshot : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private Guid _Id;

        private Guid _IngestionRunId;

        private string _SnapshotUid;

        private string _RepoUrl;

        private string _Branch;

        private string _RepoCommit;

        private string _Language;

        private string _PackageName;

        private string _PackageVersion;

        private string _ConfigJson;

        private byte[] _SnapshotUidHash;

        private ICollection<ApiType> _ApiTypes;

        private ICollection<DocPage> _DocPages;

        private ICollection<ExecutionRun> _ExecutionRuns;

        private ICollection<RagRun> _RagRuns;

        private ICollection<ReviewRun> _ReviewRuns;

        private ICollection<SampleRun> _SampleRuns;

        private ICollection<SnapshotDiff> _SnapshotDiffs_OldSnapshotId;

        private ICollection<SnapshotDiff> _SnapshotDiffs_NewSnapshotId;

        private IngestionRun _IngestionRun;

        private ICollection<TruthRun> _TruthRuns;

        public SourceSnapshot()
        {
            this._ApiTypes = new List<ApiType>();
            this._DocPages = new List<DocPage>();
            this._ExecutionRuns = new List<ExecutionRun>();
            this._RagRuns = new List<RagRun>();
            this._ReviewRuns = new List<ReviewRun>();
            this._SampleRuns = new List<SampleRun>();
            this._SnapshotDiffs_OldSnapshotId = new List<SnapshotDiff>();
            this._SnapshotDiffs_NewSnapshotId = new List<SnapshotDiff>();
            this._TruthRuns = new List<TruthRun>();
            OnCreated();
        }

        [NotNullValidator()]
        public Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging("Id");
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

        [NotNullValidator()]
        public Guid? IngestionRunId
        {
            get
            {
                return this._IngestionRunId;
            }
            set
            {
                if (this._IngestionRunId != value)
                {
                    this.OnIngestionRunIdChanging(value);
                    this.SendPropertyChanging("IngestionRunId");
                    this._IngestionRunId = (Guid)value;
                    this.SendPropertyChanged("IngestionRunId");
                    this.OnIngestionRunIdChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 1000,  RangeBoundaryType.Inclusive)]
        [NotNullValidator()]
        public string SnapshotUid
        {
            get
            {
                return this._SnapshotUid;
            }
            set
            {
                if (this._SnapshotUid != value)
                {
                    this.OnSnapshotUidChanging(value);
                    this.SendPropertyChanging("SnapshotUid");
                    this._SnapshotUid = value;
                    this.SendPropertyChanged("SnapshotUid");
                    this.OnSnapshotUidChanged();
                }
            }
        }

        public string RepoUrl
        {
            get
            {
                return this._RepoUrl;
            }
            set
            {
                if (this._RepoUrl != value)
                {
                    this.OnRepoUrlChanging(value);
                    this.SendPropertyChanging("RepoUrl");
                    this._RepoUrl = value;
                    this.SendPropertyChanged("RepoUrl");
                    this.OnRepoUrlChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 200,  RangeBoundaryType.Inclusive)]
        public string Branch
        {
            get
            {
                return this._Branch;
            }
            set
            {
                if (this._Branch != value)
                {
                    this.OnBranchChanging(value);
                    this.SendPropertyChanging("Branch");
                    this._Branch = value;
                    this.SendPropertyChanged("Branch");
                    this.OnBranchChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 200,  RangeBoundaryType.Inclusive)]
        public string RepoCommit
        {
            get
            {
                return this._RepoCommit;
            }
            set
            {
                if (this._RepoCommit != value)
                {
                    this.OnRepoCommitChanging(value);
                    this.SendPropertyChanging("RepoCommit");
                    this._RepoCommit = value;
                    this.SendPropertyChanged("RepoCommit");
                    this.OnRepoCommitChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 200,  RangeBoundaryType.Inclusive)]
        public string Language
        {
            get
            {
                return this._Language;
            }
            set
            {
                if (this._Language != value)
                {
                    this.OnLanguageChanging(value);
                    this.SendPropertyChanging("Language");
                    this._Language = value;
                    this.SendPropertyChanged("Language");
                    this.OnLanguageChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 200,  RangeBoundaryType.Inclusive)]
        public string PackageName
        {
            get
            {
                return this._PackageName;
            }
            set
            {
                if (this._PackageName != value)
                {
                    this.OnPackageNameChanging(value);
                    this.SendPropertyChanging("PackageName");
                    this._PackageName = value;
                    this.SendPropertyChanged("PackageName");
                    this.OnPackageNameChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 200,  RangeBoundaryType.Inclusive)]
        public string PackageVersion
        {
            get
            {
                return this._PackageVersion;
            }
            set
            {
                if (this._PackageVersion != value)
                {
                    this.OnPackageVersionChanging(value);
                    this.SendPropertyChanging("PackageVersion");
                    this._PackageVersion = value;
                    this.SendPropertyChanged("PackageVersion");
                    this.OnPackageVersionChanged();
                }
            }
        }

        public string ConfigJson
        {
            get
            {
                return this._ConfigJson;
            }
            set
            {
                if (this._ConfigJson != value)
                {
                    this.OnConfigJsonChanging(value);
                    this.SendPropertyChanging("ConfigJson");
                    this._ConfigJson = value;
                    this.SendPropertyChanged("ConfigJson");
                    this.OnConfigJsonChanged();
                }
            }
        }

        public byte[] SnapshotUidHash
        {
            get
            {
                return this._SnapshotUidHash;
            }
            set
            {
                if (this._SnapshotUidHash != value)
                {
                    this.OnSnapshotUidHashChanging(value);
                    this.SendPropertyChanging("SnapshotUidHash");
                    this._SnapshotUidHash = value;
                    this.SendPropertyChanged("SnapshotUidHash");
                    this.OnSnapshotUidHashChanged();
                }
            }
        }


        public virtual ICollection<ApiType> ApiTypes
        {
            get
            {
                return this._ApiTypes;
            }
            set
            {
                this._ApiTypes = value;
            }
        }


        public virtual ICollection<DocPage> DocPages
        {
            get
            {
                return this._DocPages;
            }
            set
            {
                this._DocPages = value;
            }
        }


        public virtual ICollection<ExecutionRun> ExecutionRuns
        {
            get
            {
                return this._ExecutionRuns;
            }
            set
            {
                this._ExecutionRuns = value;
            }
        }


        public virtual ICollection<RagRun> RagRuns
        {
            get
            {
                return this._RagRuns;
            }
            set
            {
                this._RagRuns = value;
            }
        }


        public virtual ICollection<ReviewRun> ReviewRuns
        {
            get
            {
                return this._ReviewRuns;
            }
            set
            {
                this._ReviewRuns = value;
            }
        }


        public virtual ICollection<SampleRun> SampleRuns
        {
            get
            {
                return this._SampleRuns;
            }
            set
            {
                this._SampleRuns = value;
            }
        }


        public virtual ICollection<SnapshotDiff> SnapshotDiffs_OldSnapshotId
        {
            get
            {
                return this._SnapshotDiffs_OldSnapshotId;
            }
            set
            {
                this._SnapshotDiffs_OldSnapshotId = value;
            }
        }


        public virtual ICollection<SnapshotDiff> SnapshotDiffs_NewSnapshotId
        {
            get
            {
                return this._SnapshotDiffs_NewSnapshotId;
            }
            set
            {
                this._SnapshotDiffs_NewSnapshotId = value;
            }
        }


        public virtual IngestionRun IngestionRun
        {
            get
            {
                return this._IngestionRun;
            }
            set
            {
                if (this._IngestionRun != value)
                {
                    this.OnIngestionRunChanging(value);
                    this.SendPropertyChanging("IngestionRun");
                    this._IngestionRun = value;
                    this.SendPropertyChanged("IngestionRun");
                    this.OnIngestionRunChanged();
                }
            }
        }


        public virtual ICollection<TruthRun> TruthRuns
        {
            get
            {
                return this._TruthRuns;
            }
            set
            {
                this._TruthRuns = value;
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();
        partial void OnIdChanging(Guid value);

        partial void OnIdChanged();
        partial void OnIngestionRunIdChanging(Guid? value);

        partial void OnIngestionRunIdChanged();
        partial void OnSnapshotUidChanging(string value);

        partial void OnSnapshotUidChanged();
        partial void OnRepoUrlChanging(string value);

        partial void OnRepoUrlChanged();
        partial void OnBranchChanging(string value);

        partial void OnBranchChanged();
        partial void OnRepoCommitChanging(string value);

        partial void OnRepoCommitChanged();
        partial void OnLanguageChanging(string value);

        partial void OnLanguageChanged();
        partial void OnPackageNameChanging(string value);

        partial void OnPackageNameChanged();
        partial void OnPackageVersionChanging(string value);

        partial void OnPackageVersionChanged();
        partial void OnConfigJsonChanging(string value);

        partial void OnConfigJsonChanged();
        partial void OnSnapshotUidHashChanging(byte[] value);

        partial void OnSnapshotUidHashChanged();
        partial void OnIngestionRunChanging(IngestionRun value);

        partial void OnIngestionRunChanged();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
