//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 1.25
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.Practices.EnterpriseLibrary.Validation.Validators;

namespace ITCompanionAI.Entities
{
    public partial class ApiType : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private Guid _Id;

        private string _SemanticUid;

        private Guid _SourceSnapshotId;

        private string _Name;

        private string _NamespacePath;

        private string _Kind;

        private string _Accessibility;

        private bool? _IsStatic;

        private bool? _IsGeneric;

        private bool? _IsAbstract;

        private bool? _IsSealed;

        private bool? _IsRecord;

        private bool? _IsRefLike;

        private string _BaseTypeUid;

        private string _Interfaces;

        private string _ContainingTypeUid;

        private string _GenericParameters;

        private string _GenericConstraints;

        private string _Summary;

        private string _Remarks;

        private string _Attributes;

        private string _SourceFilePath;

        private int? _SourceStartLine;

        private int? _SourceEndLine;

        private int _VersionNumber;

        private Guid _CreatedIngestionRunId;

        private Guid _UpdatedIngestionRunId;

        private Guid? _RemovedIngestionRunId;

        private DateTime _ValidFromUtc;

        private DateTime? _ValidToUtc;

        private bool _IsActive;

        private byte[] _ContentHash;

        private byte[] _SemanticUidHash;

        private SourceSnapshot _SourceSnapshot;

        private IngestionRun _IngestionRun_CreatedIngestionRunId;

        private IngestionRun _IngestionRun_UpdatedIngestionRunId;

        private IngestionRun _IngestionRun_RemovedIngestionRunId;

        public ApiType()
        {
            this._IsActive = true;
            OnCreated();
        }

        [NotNullValidator()]
        public Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging("Id");
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 1000,  RangeBoundaryType.Inclusive)]
        [NotNullValidator()]
        public string SemanticUid
        {
            get
            {
                return this._SemanticUid;
            }
            set
            {
                if (this._SemanticUid != value)
                {
                    this.OnSemanticUidChanging(value);
                    this.SendPropertyChanging("SemanticUid");
                    this._SemanticUid = value;
                    this.SendPropertyChanged("SemanticUid");
                    this.OnSemanticUidChanged();
                }
            }
        }

        [NotNullValidator()]
        public Guid SourceSnapshotId
        {
            get
            {
                return this._SourceSnapshotId;
            }
            set
            {
                if (this._SourceSnapshotId != value)
                {
                    this.OnSourceSnapshotIdChanging(value);
                    this.SendPropertyChanging("SourceSnapshotId");
                    this._SourceSnapshotId = value;
                    this.SendPropertyChanged("SourceSnapshotId");
                    this.OnSourceSnapshotIdChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 400,  RangeBoundaryType.Inclusive)]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if (this._Name != value)
                {
                    this.OnNameChanging(value);
                    this.SendPropertyChanging("Name");
                    this._Name = value;
                    this.SendPropertyChanged("Name");
                    this.OnNameChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 1000,  RangeBoundaryType.Inclusive)]
        public string NamespacePath
        {
            get
            {
                return this._NamespacePath;
            }
            set
            {
                if (this._NamespacePath != value)
                {
                    this.OnNamespacePathChanging(value);
                    this.SendPropertyChanging("NamespacePath");
                    this._NamespacePath = value;
                    this.SendPropertyChanged("NamespacePath");
                    this.OnNamespacePathChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 200,  RangeBoundaryType.Inclusive)]
        public string Kind
        {
            get
            {
                return this._Kind;
            }
            set
            {
                if (this._Kind != value)
                {
                    this.OnKindChanging(value);
                    this.SendPropertyChanging("Kind");
                    this._Kind = value;
                    this.SendPropertyChanged("Kind");
                    this.OnKindChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 200,  RangeBoundaryType.Inclusive)]
        public string Accessibility
        {
            get
            {
                return this._Accessibility;
            }
            set
            {
                if (this._Accessibility != value)
                {
                    this.OnAccessibilityChanging(value);
                    this.SendPropertyChanging("Accessibility");
                    this._Accessibility = value;
                    this.SendPropertyChanged("Accessibility");
                    this.OnAccessibilityChanged();
                }
            }
        }

        public bool? IsStatic
        {
            get
            {
                return this._IsStatic;
            }
            set
            {
                if (this._IsStatic != value)
                {
                    this.OnIsStaticChanging(value);
                    this.SendPropertyChanging("IsStatic");
                    this._IsStatic = value;
                    this.SendPropertyChanged("IsStatic");
                    this.OnIsStaticChanged();
                }
            }
        }

        public bool? IsGeneric
        {
            get
            {
                return this._IsGeneric;
            }
            set
            {
                if (this._IsGeneric != value)
                {
                    this.OnIsGenericChanging(value);
                    this.SendPropertyChanging("IsGeneric");
                    this._IsGeneric = value;
                    this.SendPropertyChanged("IsGeneric");
                    this.OnIsGenericChanged();
                }
            }
        }

        public bool? IsAbstract
        {
            get
            {
                return this._IsAbstract;
            }
            set
            {
                if (this._IsAbstract != value)
                {
                    this.OnIsAbstractChanging(value);
                    this.SendPropertyChanging("IsAbstract");
                    this._IsAbstract = value;
                    this.SendPropertyChanged("IsAbstract");
                    this.OnIsAbstractChanged();
                }
            }
        }

        public bool? IsSealed
        {
            get
            {
                return this._IsSealed;
            }
            set
            {
                if (this._IsSealed != value)
                {
                    this.OnIsSealedChanging(value);
                    this.SendPropertyChanging("IsSealed");
                    this._IsSealed = value;
                    this.SendPropertyChanged("IsSealed");
                    this.OnIsSealedChanged();
                }
            }
        }

        public bool? IsRecord
        {
            get
            {
                return this._IsRecord;
            }
            set
            {
                if (this._IsRecord != value)
                {
                    this.OnIsRecordChanging(value);
                    this.SendPropertyChanging("IsRecord");
                    this._IsRecord = value;
                    this.SendPropertyChanged("IsRecord");
                    this.OnIsRecordChanged();
                }
            }
        }

        public bool? IsRefLike
        {
            get
            {
                return this._IsRefLike;
            }
            set
            {
                if (this._IsRefLike != value)
                {
                    this.OnIsRefLikeChanging(value);
                    this.SendPropertyChanging("IsRefLike");
                    this._IsRefLike = value;
                    this.SendPropertyChanged("IsRefLike");
                    this.OnIsRefLikeChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 1000,  RangeBoundaryType.Inclusive)]
        public string? BaseTypeUid
        {
            get
            {
                return this._BaseTypeUid;
            }
            set
            {
                if (this._BaseTypeUid != value)
                {
                    this.OnBaseTypeUidChanging(value);
                    this.SendPropertyChanging("BaseTypeUid");
                    this._BaseTypeUid = value;
                    this.SendPropertyChanged("BaseTypeUid");
                    this.OnBaseTypeUidChanged();
                }
            }
        }

        public string Interfaces
        {
            get
            {
                return this._Interfaces;
            }
            set
            {
                if (this._Interfaces != value)
                {
                    this.OnInterfacesChanging(value);
                    this.SendPropertyChanging("Interfaces");
                    this._Interfaces = value;
                    this.SendPropertyChanged("Interfaces");
                    this.OnInterfacesChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 1000,  RangeBoundaryType.Inclusive)]
        public string? ContainingTypeUid
        {
            get
            {
                return this._ContainingTypeUid;
            }
            set
            {
                if (this._ContainingTypeUid != value)
                {
                    this.OnContainingTypeUidChanging(value);
                    this.SendPropertyChanging("ContainingTypeUid");
                    this._ContainingTypeUid = value;
                    this.SendPropertyChanged("ContainingTypeUid");
                    this.OnContainingTypeUidChanged();
                }
            }
        }

        public string GenericParameters
        {
            get
            {
                return this._GenericParameters;
            }
            set
            {
                if (this._GenericParameters != value)
                {
                    this.OnGenericParametersChanging(value);
                    this.SendPropertyChanging("GenericParameters");
                    this._GenericParameters = value;
                    this.SendPropertyChanged("GenericParameters");
                    this.OnGenericParametersChanged();
                }
            }
        }

        public string GenericConstraints
        {
            get
            {
                return this._GenericConstraints;
            }
            set
            {
                if (this._GenericConstraints != value)
                {
                    this.OnGenericConstraintsChanging(value);
                    this.SendPropertyChanging("GenericConstraints");
                    this._GenericConstraints = value;
                    this.SendPropertyChanged("GenericConstraints");
                    this.OnGenericConstraintsChanged();
                }
            }
        }

        public string Summary
        {
            get
            {
                return this._Summary;
            }
            set
            {
                if (this._Summary != value)
                {
                    this.OnSummaryChanging(value);
                    this.SendPropertyChanging("Summary");
                    this._Summary = value;
                    this.SendPropertyChanged("Summary");
                    this.OnSummaryChanged();
                }
            }
        }

        public string Remarks
        {
            get
            {
                return this._Remarks;
            }
            set
            {
                if (this._Remarks != value)
                {
                    this.OnRemarksChanging(value);
                    this.SendPropertyChanging("Remarks");
                    this._Remarks = value;
                    this.SendPropertyChanged("Remarks");
                    this.OnRemarksChanged();
                }
            }
        }

        public string Attributes
        {
            get
            {
                return this._Attributes;
            }
            set
            {
                if (this._Attributes != value)
                {
                    this.OnAttributesChanging(value);
                    this.SendPropertyChanging("Attributes");
                    this._Attributes = value;
                    this.SendPropertyChanged("Attributes");
                    this.OnAttributesChanged();
                }
            }
        }

        public string SourceFilePath
        {
            get
            {
                return this._SourceFilePath;
            }
            set
            {
                if (this._SourceFilePath != value)
                {
                    this.OnSourceFilePathChanging(value);
                    this.SendPropertyChanging("SourceFilePath");
                    this._SourceFilePath = value;
                    this.SendPropertyChanged("SourceFilePath");
                    this.OnSourceFilePathChanged();
                }
            }
        }

        public int? SourceStartLine
        {
            get
            {
                return this._SourceStartLine;
            }
            set
            {
                if (this._SourceStartLine != value)
                {
                    this.OnSourceStartLineChanging(value);
                    this.SendPropertyChanging("SourceStartLine");
                    this._SourceStartLine = value;
                    this.SendPropertyChanged("SourceStartLine");
                    this.OnSourceStartLineChanged();
                }
            }
        }

        public int? SourceEndLine
        {
            get
            {
                return this._SourceEndLine;
            }
            set
            {
                if (this._SourceEndLine != value)
                {
                    this.OnSourceEndLineChanging(value);
                    this.SendPropertyChanging("SourceEndLine");
                    this._SourceEndLine = value;
                    this.SendPropertyChanged("SourceEndLine");
                    this.OnSourceEndLineChanged();
                }
            }
        }

        [NotNullValidator()]
        public int VersionNumber
        {
            get
            {
                return this._VersionNumber;
            }
            set
            {
                if (this._VersionNumber != value)
                {
                    this.OnVersionNumberChanging(value);
                    this.SendPropertyChanging("VersionNumber");
                    this._VersionNumber = value;
                    this.SendPropertyChanged("VersionNumber");
                    this.OnVersionNumberChanged();
                }
            }
        }

        [NotNullValidator()]
        public Guid CreatedIngestionRunId
        {
            get
            {
                return this._CreatedIngestionRunId;
            }
            set
            {
                if (this._CreatedIngestionRunId != value)
                {
                    this.OnCreatedIngestionRunIdChanging(value);
                    this.SendPropertyChanging("CreatedIngestionRunId");
                    this._CreatedIngestionRunId = value;
                    this.SendPropertyChanged("CreatedIngestionRunId");
                    this.OnCreatedIngestionRunIdChanged();
                }
            }
        }

        [NotNullValidator()]
        public Guid UpdatedIngestionRunId
        {
            get
            {
                return this._UpdatedIngestionRunId;
            }
            set
            {
                if (this._UpdatedIngestionRunId != value)
                {
                    this.OnUpdatedIngestionRunIdChanging(value);
                    this.SendPropertyChanging("UpdatedIngestionRunId");
                    this._UpdatedIngestionRunId = value;
                    this.SendPropertyChanged("UpdatedIngestionRunId");
                    this.OnUpdatedIngestionRunIdChanged();
                }
            }
        }

        public Guid? RemovedIngestionRunId
        {
            get
            {
                return this._RemovedIngestionRunId;
            }
            set
            {
                if (this._RemovedIngestionRunId != value)
                {
                    this.OnRemovedIngestionRunIdChanging(value);
                    this.SendPropertyChanging("RemovedIngestionRunId");
                    this._RemovedIngestionRunId = value;
                    this.SendPropertyChanged("RemovedIngestionRunId");
                    this.OnRemovedIngestionRunIdChanged();
                }
            }
        }

        [NotNullValidator()]
        public DateTime ValidFromUtc
        {
            get
            {
                return this._ValidFromUtc;
            }
            set
            {
                if (this._ValidFromUtc != value)
                {
                    this.OnValidFromUtcChanging(value);
                    this.SendPropertyChanging("ValidFromUtc");
                    this._ValidFromUtc = value;
                    this.SendPropertyChanged("ValidFromUtc");
                    this.OnValidFromUtcChanged();
                }
            }
        }

        public DateTime? ValidToUtc
        {
            get
            {
                return this._ValidToUtc;
            }
            set
            {
                if (this._ValidToUtc != value)
                {
                    this.OnValidToUtcChanging(value);
                    this.SendPropertyChanging("ValidToUtc");
                    this._ValidToUtc = value;
                    this.SendPropertyChanged("ValidToUtc");
                    this.OnValidToUtcChanged();
                }
            }
        }

        [NotNullValidator()]
        public bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                if (this._IsActive != value)
                {
                    this.OnIsActiveChanging(value);
                    this.SendPropertyChanging("IsActive");
                    this._IsActive = value;
                    this.SendPropertyChanged("IsActive");
                    this.OnIsActiveChanged();
                }
            }
        }

        public byte[] ContentHash
        {
            get
            {
                return this._ContentHash;
            }
            set
            {
                if (this._ContentHash != value)
                {
                    this.OnContentHashChanging(value);
                    this.SendPropertyChanging("ContentHash");
                    this._ContentHash = value;
                    this.SendPropertyChanged("ContentHash");
                    this.OnContentHashChanged();
                }
            }
        }

        public byte[] SemanticUidHash
        {
            get
            {
                return this._SemanticUidHash;
            }
            set
            {
                if (this._SemanticUidHash != value)
                {
                    this.OnSemanticUidHashChanging(value);
                    this.SendPropertyChanging("SemanticUidHash");
                    this._SemanticUidHash = value;
                    this.SendPropertyChanged("SemanticUidHash");
                    this.OnSemanticUidHashChanged();
                }
            }
        }


        public virtual SourceSnapshot SourceSnapshot
        {
            get
            {
                return this._SourceSnapshot;
            }
            set
            {
                if (this._SourceSnapshot != value)
                {
                    this.OnSourceSnapshotChanging(value);
                    this.SendPropertyChanging("SourceSnapshot");
                    this._SourceSnapshot = value;
                    this.SendPropertyChanged("SourceSnapshot");
                    this.OnSourceSnapshotChanged();
                }
            }
        }


        public virtual IngestionRun IngestionRun_CreatedIngestionRunId
        {
            get
            {
                return this._IngestionRun_CreatedIngestionRunId;
            }
            set
            {
                if (this._IngestionRun_CreatedIngestionRunId != value)
                {
                    this.OnIngestionRun_CreatedIngestionRunIdChanging(value);
                    this.SendPropertyChanging("IngestionRun_CreatedIngestionRunId");
                    this._IngestionRun_CreatedIngestionRunId = value;
                    this.SendPropertyChanged("IngestionRun_CreatedIngestionRunId");
                    this.OnIngestionRun_CreatedIngestionRunIdChanged();
                }
            }
        }


        public virtual IngestionRun IngestionRun_UpdatedIngestionRunId
        {
            get
            {
                return this._IngestionRun_UpdatedIngestionRunId;
            }
            set
            {
                if (this._IngestionRun_UpdatedIngestionRunId != value)
                {
                    this.OnIngestionRun_UpdatedIngestionRunIdChanging(value);
                    this.SendPropertyChanging("IngestionRun_UpdatedIngestionRunId");
                    this._IngestionRun_UpdatedIngestionRunId = value;
                    this.SendPropertyChanged("IngestionRun_UpdatedIngestionRunId");
                    this.OnIngestionRun_UpdatedIngestionRunIdChanged();
                }
            }
        }


        public virtual IngestionRun IngestionRun_RemovedIngestionRunId
        {
            get
            {
                return this._IngestionRun_RemovedIngestionRunId;
            }
            set
            {
                if (this._IngestionRun_RemovedIngestionRunId != value)
                {
                    this.OnIngestionRun_RemovedIngestionRunIdChanging(value);
                    this.SendPropertyChanging("IngestionRun_RemovedIngestionRunId");
                    this._IngestionRun_RemovedIngestionRunId = value;
                    this.SendPropertyChanged("IngestionRun_RemovedIngestionRunId");
                    this.OnIngestionRun_RemovedIngestionRunIdChanged();
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();
        partial void OnIdChanging(Guid value);

        partial void OnIdChanged();
        partial void OnSemanticUidChanging(string value);

        partial void OnSemanticUidChanged();
        partial void OnSourceSnapshotIdChanging(Guid value);

        partial void OnSourceSnapshotIdChanged();
        partial void OnNameChanging(string value);

        partial void OnNameChanged();
        partial void OnNamespacePathChanging(string value);

        partial void OnNamespacePathChanged();
        partial void OnKindChanging(string value);

        partial void OnKindChanged();
        partial void OnAccessibilityChanging(string value);

        partial void OnAccessibilityChanged();
        partial void OnIsStaticChanging(bool? value);

        partial void OnIsStaticChanged();
        partial void OnIsGenericChanging(bool? value);

        partial void OnIsGenericChanged();
        partial void OnIsAbstractChanging(bool? value);

        partial void OnIsAbstractChanged();
        partial void OnIsSealedChanging(bool? value);

        partial void OnIsSealedChanged();
        partial void OnIsRecordChanging(bool? value);

        partial void OnIsRecordChanged();
        partial void OnIsRefLikeChanging(bool? value);

        partial void OnIsRefLikeChanged();
        partial void OnBaseTypeUidChanging(string value);

        partial void OnBaseTypeUidChanged();
        partial void OnInterfacesChanging(string value);

        partial void OnInterfacesChanged();
        partial void OnContainingTypeUidChanging(string value);

        partial void OnContainingTypeUidChanged();
        partial void OnGenericParametersChanging(string value);

        partial void OnGenericParametersChanged();
        partial void OnGenericConstraintsChanging(string value);

        partial void OnGenericConstraintsChanged();
        partial void OnSummaryChanging(string value);

        partial void OnSummaryChanged();
        partial void OnRemarksChanging(string value);

        partial void OnRemarksChanged();
        partial void OnAttributesChanging(string value);

        partial void OnAttributesChanged();
        partial void OnSourceFilePathChanging(string value);

        partial void OnSourceFilePathChanged();
        partial void OnSourceStartLineChanging(int? value);

        partial void OnSourceStartLineChanged();
        partial void OnSourceEndLineChanging(int? value);

        partial void OnSourceEndLineChanged();
        partial void OnVersionNumberChanging(int value);

        partial void OnVersionNumberChanged();
        partial void OnCreatedIngestionRunIdChanging(Guid value);

        partial void OnCreatedIngestionRunIdChanged();
        partial void OnUpdatedIngestionRunIdChanging(Guid value);

        partial void OnUpdatedIngestionRunIdChanged();
        partial void OnRemovedIngestionRunIdChanging(Guid? value);

        partial void OnRemovedIngestionRunIdChanged();
        partial void OnValidFromUtcChanging(DateTime value);

        partial void OnValidFromUtcChanged();
        partial void OnValidToUtcChanging(DateTime? value);

        partial void OnValidToUtcChanged();
        partial void OnIsActiveChanging(bool value);

        partial void OnIsActiveChanged();
        partial void OnContentHashChanging(byte[] value);

        partial void OnContentHashChanged();
        partial void OnSemanticUidHashChanging(byte[] value);

        partial void OnSemanticUidHashChanged();
        partial void OnSourceSnapshotChanging(SourceSnapshot value);

        partial void OnSourceSnapshotChanged();
        partial void OnIngestionRun_CreatedIngestionRunIdChanging(IngestionRun value);

        partial void OnIngestionRun_CreatedIngestionRunIdChanged();
        partial void OnIngestionRun_UpdatedIngestionRunIdChanging(IngestionRun value);

        partial void OnIngestionRun_UpdatedIngestionRunIdChanged();
        partial void OnIngestionRun_RemovedIngestionRunIdChanging(IngestionRun value);

        partial void OnIngestionRun_RemovedIngestionRunIdChanged();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
