//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 1.25
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.Practices.EnterpriseLibrary.Validation.Validators;

namespace ITCompanionAI.Entities
{
    public partial class GetChangesInIngestionRunResult : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private string _ArtifactKind;

        private string _SemanticUid;

        private int _VersionNumber;

        private DateTime _ValidFromUtc;

        private DateTime? _ValidToUtc;

        public GetChangesInIngestionRunResult()
        {
            OnCreated();
        }

        [NotNullValidator()]
        public string ArtifactKind
        {
            get
            {
                return this._ArtifactKind;
            }
            set
            {
                if (this._ArtifactKind != value)
                {
                    this.OnArtifactKindChanging(value);
                    this.SendPropertyChanging("ArtifactKind");
                    this._ArtifactKind = value;
                    this.SendPropertyChanged("ArtifactKind");
                    this.OnArtifactKindChanged();
                }
            }
        }

        [NotNullValidator()]
        public string SemanticUid
        {
            get
            {
                return this._SemanticUid;
            }
            set
            {
                if (this._SemanticUid != value)
                {
                    this.OnSemanticUidChanging(value);
                    this.SendPropertyChanging("SemanticUid");
                    this._SemanticUid = value;
                    this.SendPropertyChanged("SemanticUid");
                    this.OnSemanticUidChanged();
                }
            }
        }

        [NotNullValidator()]
        public int VersionNumber
        {
            get
            {
                return this._VersionNumber;
            }
            set
            {
                if (this._VersionNumber != value)
                {
                    this.OnVersionNumberChanging(value);
                    this.SendPropertyChanging("VersionNumber");
                    this._VersionNumber = value;
                    this.SendPropertyChanged("VersionNumber");
                    this.OnVersionNumberChanged();
                }
            }
        }

        [NotNullValidator()]
        public DateTime ValidFromUtc
        {
            get
            {
                return this._ValidFromUtc;
            }
            set
            {
                if (this._ValidFromUtc != value)
                {
                    this.OnValidFromUtcChanging(value);
                    this.SendPropertyChanging("ValidFromUtc");
                    this._ValidFromUtc = value;
                    this.SendPropertyChanged("ValidFromUtc");
                    this.OnValidFromUtcChanged();
                }
            }
        }

        public DateTime? ValidToUtc
        {
            get
            {
                return this._ValidToUtc;
            }
            set
            {
                if (this._ValidToUtc != value)
                {
                    this.OnValidToUtcChanging(value);
                    this.SendPropertyChanging("ValidToUtc");
                    this._ValidToUtc = value;
                    this.SendPropertyChanged("ValidToUtc");
                    this.OnValidToUtcChanged();
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();
        partial void OnArtifactKindChanging(string value);

        partial void OnArtifactKindChanged();
        partial void OnSemanticUidChanging(string value);

        partial void OnSemanticUidChanged();
        partial void OnVersionNumberChanging(int value);

        partial void OnVersionNumberChanged();
        partial void OnValidFromUtcChanging(DateTime value);

        partial void OnValidFromUtcChanged();
        partial void OnValidToUtcChanging(DateTime? value);

        partial void OnValidToUtcChanged();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
