//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 1.25
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.Practices.EnterpriseLibrary.Validation.Validators;

namespace ITCompanionAI.Entities
{
    public partial class VApiMemberCurrent : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private Guid _Id;

        private string _SemanticUid;

        private Guid _ApiTypeId;

        private string _Name;

        private string _Kind;

        private string _MethodKind;

        private string _Accessibility;

        private bool? _IsStatic;

        private bool? _IsExtensionMethod;

        private bool? _IsAsync;

        private bool? _IsVirtual;

        private bool? _IsOverride;

        private bool? _IsAbstract;

        private bool? _IsSealed;

        private bool? _IsReadonly;

        private bool? _IsConst;

        private bool? _IsUnsafe;

        private string _ReturnTypeUid;

        private string _ReturnNullable;

        private string _GenericParameters;

        private string _GenericConstraints;

        private string _Summary;

        private string _Remarks;

        private string _Attributes;

        private string _SourceFilePath;

        private int? _SourceStartLine;

        private int? _SourceEndLine;

        private byte[] _MemberUidHash;

        private int _VersionNumber;

        private Guid _CreatedIngestionRunId;

        private Guid _UpdatedIngestionRunId;

        private Guid? _RemovedIngestionRunId;

        private DateTime _ValidFromUtc;

        private DateTime? _ValidToUtc;

        private bool _IsActive;

        private byte[] _ContentHash;

        private byte[] _SemanticUidHash;

        public VApiMemberCurrent()
        {
            OnCreated();
        }

        [NotNullValidator()]
        public Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging("Id");
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 1000,  RangeBoundaryType.Inclusive)]
        [NotNullValidator()]
        public string SemanticUid
        {
            get
            {
                return this._SemanticUid;
            }
            set
            {
                if (this._SemanticUid != value)
                {
                    this.OnSemanticUidChanging(value);
                    this.SendPropertyChanging("SemanticUid");
                    this._SemanticUid = value;
                    this.SendPropertyChanged("SemanticUid");
                    this.OnSemanticUidChanged();
                }
            }
        }

        [NotNullValidator()]
        public Guid ApiTypeId
        {
            get
            {
                return this._ApiTypeId;
            }
            set
            {
                if (this._ApiTypeId != value)
                {
                    this.OnApiTypeIdChanging(value);
                    this.SendPropertyChanging("ApiTypeId");
                    this._ApiTypeId = value;
                    this.SendPropertyChanged("ApiTypeId");
                    this.OnApiTypeIdChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 400,  RangeBoundaryType.Inclusive)]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if (this._Name != value)
                {
                    this.OnNameChanging(value);
                    this.SendPropertyChanging("Name");
                    this._Name = value;
                    this.SendPropertyChanged("Name");
                    this.OnNameChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 200,  RangeBoundaryType.Inclusive)]
        public string Kind
        {
            get
            {
                return this._Kind;
            }
            set
            {
                if (this._Kind != value)
                {
                    this.OnKindChanging(value);
                    this.SendPropertyChanging("Kind");
                    this._Kind = value;
                    this.SendPropertyChanged("Kind");
                    this.OnKindChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 200,  RangeBoundaryType.Inclusive)]
        public string MethodKind
        {
            get
            {
                return this._MethodKind;
            }
            set
            {
                if (this._MethodKind != value)
                {
                    this.OnMethodKindChanging(value);
                    this.SendPropertyChanging("MethodKind");
                    this._MethodKind = value;
                    this.SendPropertyChanged("MethodKind");
                    this.OnMethodKindChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 200,  RangeBoundaryType.Inclusive)]
        public string Accessibility
        {
            get
            {
                return this._Accessibility;
            }
            set
            {
                if (this._Accessibility != value)
                {
                    this.OnAccessibilityChanging(value);
                    this.SendPropertyChanging("Accessibility");
                    this._Accessibility = value;
                    this.SendPropertyChanged("Accessibility");
                    this.OnAccessibilityChanged();
                }
            }
        }

        public bool? IsStatic
        {
            get
            {
                return this._IsStatic;
            }
            set
            {
                if (this._IsStatic != value)
                {
                    this.OnIsStaticChanging(value);
                    this.SendPropertyChanging("IsStatic");
                    this._IsStatic = value;
                    this.SendPropertyChanged("IsStatic");
                    this.OnIsStaticChanged();
                }
            }
        }

        public bool? IsExtensionMethod
        {
            get
            {
                return this._IsExtensionMethod;
            }
            set
            {
                if (this._IsExtensionMethod != value)
                {
                    this.OnIsExtensionMethodChanging(value);
                    this.SendPropertyChanging("IsExtensionMethod");
                    this._IsExtensionMethod = value;
                    this.SendPropertyChanged("IsExtensionMethod");
                    this.OnIsExtensionMethodChanged();
                }
            }
        }

        public bool? IsAsync
        {
            get
            {
                return this._IsAsync;
            }
            set
            {
                if (this._IsAsync != value)
                {
                    this.OnIsAsyncChanging(value);
                    this.SendPropertyChanging("IsAsync");
                    this._IsAsync = value;
                    this.SendPropertyChanged("IsAsync");
                    this.OnIsAsyncChanged();
                }
            }
        }

        public bool? IsVirtual
        {
            get
            {
                return this._IsVirtual;
            }
            set
            {
                if (this._IsVirtual != value)
                {
                    this.OnIsVirtualChanging(value);
                    this.SendPropertyChanging("IsVirtual");
                    this._IsVirtual = value;
                    this.SendPropertyChanged("IsVirtual");
                    this.OnIsVirtualChanged();
                }
            }
        }

        public bool? IsOverride
        {
            get
            {
                return this._IsOverride;
            }
            set
            {
                if (this._IsOverride != value)
                {
                    this.OnIsOverrideChanging(value);
                    this.SendPropertyChanging("IsOverride");
                    this._IsOverride = value;
                    this.SendPropertyChanged("IsOverride");
                    this.OnIsOverrideChanged();
                }
            }
        }

        public bool? IsAbstract
        {
            get
            {
                return this._IsAbstract;
            }
            set
            {
                if (this._IsAbstract != value)
                {
                    this.OnIsAbstractChanging(value);
                    this.SendPropertyChanging("IsAbstract");
                    this._IsAbstract = value;
                    this.SendPropertyChanged("IsAbstract");
                    this.OnIsAbstractChanged();
                }
            }
        }

        public bool? IsSealed
        {
            get
            {
                return this._IsSealed;
            }
            set
            {
                if (this._IsSealed != value)
                {
                    this.OnIsSealedChanging(value);
                    this.SendPropertyChanging("IsSealed");
                    this._IsSealed = value;
                    this.SendPropertyChanged("IsSealed");
                    this.OnIsSealedChanged();
                }
            }
        }

        public bool? IsReadonly
        {
            get
            {
                return this._IsReadonly;
            }
            set
            {
                if (this._IsReadonly != value)
                {
                    this.OnIsReadonlyChanging(value);
                    this.SendPropertyChanging("IsReadonly");
                    this._IsReadonly = value;
                    this.SendPropertyChanged("IsReadonly");
                    this.OnIsReadonlyChanged();
                }
            }
        }

        public bool? IsConst
        {
            get
            {
                return this._IsConst;
            }
            set
            {
                if (this._IsConst != value)
                {
                    this.OnIsConstChanging(value);
                    this.SendPropertyChanging("IsConst");
                    this._IsConst = value;
                    this.SendPropertyChanged("IsConst");
                    this.OnIsConstChanged();
                }
            }
        }

        public bool? IsUnsafe
        {
            get
            {
                return this._IsUnsafe;
            }
            set
            {
                if (this._IsUnsafe != value)
                {
                    this.OnIsUnsafeChanging(value);
                    this.SendPropertyChanging("IsUnsafe");
                    this._IsUnsafe = value;
                    this.SendPropertyChanged("IsUnsafe");
                    this.OnIsUnsafeChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 1000,  RangeBoundaryType.Inclusive)]
        public string ReturnTypeUid
        {
            get
            {
                return this._ReturnTypeUid;
            }
            set
            {
                if (this._ReturnTypeUid != value)
                {
                    this.OnReturnTypeUidChanging(value);
                    this.SendPropertyChanging("ReturnTypeUid");
                    this._ReturnTypeUid = value;
                    this.SendPropertyChanged("ReturnTypeUid");
                    this.OnReturnTypeUidChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 50,  RangeBoundaryType.Inclusive)]
        public string ReturnNullable
        {
            get
            {
                return this._ReturnNullable;
            }
            set
            {
                if (this._ReturnNullable != value)
                {
                    this.OnReturnNullableChanging(value);
                    this.SendPropertyChanging("ReturnNullable");
                    this._ReturnNullable = value;
                    this.SendPropertyChanged("ReturnNullable");
                    this.OnReturnNullableChanged();
                }
            }
        }

        public string GenericParameters
        {
            get
            {
                return this._GenericParameters;
            }
            set
            {
                if (this._GenericParameters != value)
                {
                    this.OnGenericParametersChanging(value);
                    this.SendPropertyChanging("GenericParameters");
                    this._GenericParameters = value;
                    this.SendPropertyChanged("GenericParameters");
                    this.OnGenericParametersChanged();
                }
            }
        }

        public string GenericConstraints
        {
            get
            {
                return this._GenericConstraints;
            }
            set
            {
                if (this._GenericConstraints != value)
                {
                    this.OnGenericConstraintsChanging(value);
                    this.SendPropertyChanging("GenericConstraints");
                    this._GenericConstraints = value;
                    this.SendPropertyChanged("GenericConstraints");
                    this.OnGenericConstraintsChanged();
                }
            }
        }

        public string Summary
        {
            get
            {
                return this._Summary;
            }
            set
            {
                if (this._Summary != value)
                {
                    this.OnSummaryChanging(value);
                    this.SendPropertyChanging("Summary");
                    this._Summary = value;
                    this.SendPropertyChanged("Summary");
                    this.OnSummaryChanged();
                }
            }
        }

        public string Remarks
        {
            get
            {
                return this._Remarks;
            }
            set
            {
                if (this._Remarks != value)
                {
                    this.OnRemarksChanging(value);
                    this.SendPropertyChanging("Remarks");
                    this._Remarks = value;
                    this.SendPropertyChanged("Remarks");
                    this.OnRemarksChanged();
                }
            }
        }

        public string Attributes
        {
            get
            {
                return this._Attributes;
            }
            set
            {
                if (this._Attributes != value)
                {
                    this.OnAttributesChanging(value);
                    this.SendPropertyChanging("Attributes");
                    this._Attributes = value;
                    this.SendPropertyChanged("Attributes");
                    this.OnAttributesChanged();
                }
            }
        }

        public string SourceFilePath
        {
            get
            {
                return this._SourceFilePath;
            }
            set
            {
                if (this._SourceFilePath != value)
                {
                    this.OnSourceFilePathChanging(value);
                    this.SendPropertyChanging("SourceFilePath");
                    this._SourceFilePath = value;
                    this.SendPropertyChanged("SourceFilePath");
                    this.OnSourceFilePathChanged();
                }
            }
        }

        public int? SourceStartLine
        {
            get
            {
                return this._SourceStartLine;
            }
            set
            {
                if (this._SourceStartLine != value)
                {
                    this.OnSourceStartLineChanging(value);
                    this.SendPropertyChanging("SourceStartLine");
                    this._SourceStartLine = value;
                    this.SendPropertyChanged("SourceStartLine");
                    this.OnSourceStartLineChanged();
                }
            }
        }

        public int? SourceEndLine
        {
            get
            {
                return this._SourceEndLine;
            }
            set
            {
                if (this._SourceEndLine != value)
                {
                    this.OnSourceEndLineChanging(value);
                    this.SendPropertyChanging("SourceEndLine");
                    this._SourceEndLine = value;
                    this.SendPropertyChanged("SourceEndLine");
                    this.OnSourceEndLineChanged();
                }
            }
        }

        public byte[] MemberUidHash
        {
            get
            {
                return this._MemberUidHash;
            }
            set
            {
                if (this._MemberUidHash != value)
                {
                    this.OnMemberUidHashChanging(value);
                    this.SendPropertyChanging("MemberUidHash");
                    this._MemberUidHash = value;
                    this.SendPropertyChanged("MemberUidHash");
                    this.OnMemberUidHashChanged();
                }
            }
        }

        [NotNullValidator()]
        public int VersionNumber
        {
            get
            {
                return this._VersionNumber;
            }
            set
            {
                if (this._VersionNumber != value)
                {
                    this.OnVersionNumberChanging(value);
                    this.SendPropertyChanging("VersionNumber");
                    this._VersionNumber = value;
                    this.SendPropertyChanged("VersionNumber");
                    this.OnVersionNumberChanged();
                }
            }
        }

        [NotNullValidator()]
        public Guid CreatedIngestionRunId
        {
            get
            {
                return this._CreatedIngestionRunId;
            }
            set
            {
                if (this._CreatedIngestionRunId != value)
                {
                    this.OnCreatedIngestionRunIdChanging(value);
                    this.SendPropertyChanging("CreatedIngestionRunId");
                    this._CreatedIngestionRunId = value;
                    this.SendPropertyChanged("CreatedIngestionRunId");
                    this.OnCreatedIngestionRunIdChanged();
                }
            }
        }

        [NotNullValidator()]
        public Guid UpdatedIngestionRunId
        {
            get
            {
                return this._UpdatedIngestionRunId;
            }
            set
            {
                if (this._UpdatedIngestionRunId != value)
                {
                    this.OnUpdatedIngestionRunIdChanging(value);
                    this.SendPropertyChanging("UpdatedIngestionRunId");
                    this._UpdatedIngestionRunId = value;
                    this.SendPropertyChanged("UpdatedIngestionRunId");
                    this.OnUpdatedIngestionRunIdChanged();
                }
            }
        }

        public Guid? RemovedIngestionRunId
        {
            get
            {
                return this._RemovedIngestionRunId;
            }
            set
            {
                if (this._RemovedIngestionRunId != value)
                {
                    this.OnRemovedIngestionRunIdChanging(value);
                    this.SendPropertyChanging("RemovedIngestionRunId");
                    this._RemovedIngestionRunId = value;
                    this.SendPropertyChanged("RemovedIngestionRunId");
                    this.OnRemovedIngestionRunIdChanged();
                }
            }
        }

        [NotNullValidator()]
        public DateTime ValidFromUtc
        {
            get
            {
                return this._ValidFromUtc;
            }
            set
            {
                if (this._ValidFromUtc != value)
                {
                    this.OnValidFromUtcChanging(value);
                    this.SendPropertyChanging("ValidFromUtc");
                    this._ValidFromUtc = value;
                    this.SendPropertyChanged("ValidFromUtc");
                    this.OnValidFromUtcChanged();
                }
            }
        }

        public DateTime? ValidToUtc
        {
            get
            {
                return this._ValidToUtc;
            }
            set
            {
                if (this._ValidToUtc != value)
                {
                    this.OnValidToUtcChanging(value);
                    this.SendPropertyChanging("ValidToUtc");
                    this._ValidToUtc = value;
                    this.SendPropertyChanged("ValidToUtc");
                    this.OnValidToUtcChanged();
                }
            }
        }

        [NotNullValidator()]
        public bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                if (this._IsActive != value)
                {
                    this.OnIsActiveChanging(value);
                    this.SendPropertyChanging("IsActive");
                    this._IsActive = value;
                    this.SendPropertyChanged("IsActive");
                    this.OnIsActiveChanged();
                }
            }
        }

        public byte[] ContentHash
        {
            get
            {
                return this._ContentHash;
            }
            set
            {
                if (this._ContentHash != value)
                {
                    this.OnContentHashChanging(value);
                    this.SendPropertyChanging("ContentHash");
                    this._ContentHash = value;
                    this.SendPropertyChanged("ContentHash");
                    this.OnContentHashChanged();
                }
            }
        }

        public byte[] SemanticUidHash
        {
            get
            {
                return this._SemanticUidHash;
            }
            set
            {
                if (this._SemanticUidHash != value)
                {
                    this.OnSemanticUidHashChanging(value);
                    this.SendPropertyChanging("SemanticUidHash");
                    this._SemanticUidHash = value;
                    this.SendPropertyChanged("SemanticUidHash");
                    this.OnSemanticUidHashChanged();
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();
        partial void OnIdChanging(Guid value);

        partial void OnIdChanged();
        partial void OnSemanticUidChanging(string value);

        partial void OnSemanticUidChanged();
        partial void OnApiTypeIdChanging(Guid value);

        partial void OnApiTypeIdChanged();
        partial void OnNameChanging(string value);

        partial void OnNameChanged();
        partial void OnKindChanging(string value);

        partial void OnKindChanged();
        partial void OnMethodKindChanging(string value);

        partial void OnMethodKindChanged();
        partial void OnAccessibilityChanging(string value);

        partial void OnAccessibilityChanged();
        partial void OnIsStaticChanging(bool? value);

        partial void OnIsStaticChanged();
        partial void OnIsExtensionMethodChanging(bool? value);

        partial void OnIsExtensionMethodChanged();
        partial void OnIsAsyncChanging(bool? value);

        partial void OnIsAsyncChanged();
        partial void OnIsVirtualChanging(bool? value);

        partial void OnIsVirtualChanged();
        partial void OnIsOverrideChanging(bool? value);

        partial void OnIsOverrideChanged();
        partial void OnIsAbstractChanging(bool? value);

        partial void OnIsAbstractChanged();
        partial void OnIsSealedChanging(bool? value);

        partial void OnIsSealedChanged();
        partial void OnIsReadonlyChanging(bool? value);

        partial void OnIsReadonlyChanged();
        partial void OnIsConstChanging(bool? value);

        partial void OnIsConstChanged();
        partial void OnIsUnsafeChanging(bool? value);

        partial void OnIsUnsafeChanged();
        partial void OnReturnTypeUidChanging(string value);

        partial void OnReturnTypeUidChanged();
        partial void OnReturnNullableChanging(string value);

        partial void OnReturnNullableChanged();
        partial void OnGenericParametersChanging(string value);

        partial void OnGenericParametersChanged();
        partial void OnGenericConstraintsChanging(string value);

        partial void OnGenericConstraintsChanged();
        partial void OnSummaryChanging(string value);

        partial void OnSummaryChanged();
        partial void OnRemarksChanging(string value);

        partial void OnRemarksChanged();
        partial void OnAttributesChanging(string value);

        partial void OnAttributesChanged();
        partial void OnSourceFilePathChanging(string value);

        partial void OnSourceFilePathChanged();
        partial void OnSourceStartLineChanging(int? value);

        partial void OnSourceStartLineChanged();
        partial void OnSourceEndLineChanging(int? value);

        partial void OnSourceEndLineChanged();
        partial void OnMemberUidHashChanging(byte[] value);

        partial void OnMemberUidHashChanged();
        partial void OnVersionNumberChanging(int value);

        partial void OnVersionNumberChanged();
        partial void OnCreatedIngestionRunIdChanging(Guid value);

        partial void OnCreatedIngestionRunIdChanged();
        partial void OnUpdatedIngestionRunIdChanging(Guid value);

        partial void OnUpdatedIngestionRunIdChanged();
        partial void OnRemovedIngestionRunIdChanging(Guid? value);

        partial void OnRemovedIngestionRunIdChanged();
        partial void OnValidFromUtcChanging(DateTime value);

        partial void OnValidFromUtcChanged();
        partial void OnValidToUtcChanging(DateTime? value);

        partial void OnValidToUtcChanged();
        partial void OnIsActiveChanging(bool value);

        partial void OnIsActiveChanged();
        partial void OnContentHashChanging(byte[] value);

        partial void OnContentHashChanged();
        partial void OnSemanticUidHashChanging(byte[] value);

        partial void OnSemanticUidHashChanged();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
