//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 1.25
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.Practices.EnterpriseLibrary.Validation.Validators;

namespace ITCompanionAI.Entities
{
    public partial class ExecutionRun : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private Guid _Id;

        private Guid _SnapshotId;

        private Guid _SampleRunId;

        private DateTime _TimestampUtc;

        private string _EnvironmentJson;

        private string _SchemaVersion;

        private ICollection<ExecutionResult> _ExecutionResults;

        private SourceSnapshot _SourceSnapshot;

        private SampleRun _SampleRun;

        public ExecutionRun()
        {
            this._ExecutionResults = new List<ExecutionResult>();
            OnCreated();
        }

        [NotNullValidator()]
        public Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging("Id");
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

        [NotNullValidator()]
        public Guid SnapshotId
        {
            get
            {
                return this._SnapshotId;
            }
            set
            {
                if (this._SnapshotId != value)
                {
                    this.OnSnapshotIdChanging(value);
                    this.SendPropertyChanging("SnapshotId");
                    this._SnapshotId = value;
                    this.SendPropertyChanged("SnapshotId");
                    this.OnSnapshotIdChanged();
                }
            }
        }

        [NotNullValidator()]
        public Guid SampleRunId
        {
            get
            {
                return this._SampleRunId;
            }
            set
            {
                if (this._SampleRunId != value)
                {
                    this.OnSampleRunIdChanging(value);
                    this.SendPropertyChanging("SampleRunId");
                    this._SampleRunId = value;
                    this.SendPropertyChanged("SampleRunId");
                    this.OnSampleRunIdChanged();
                }
            }
        }

        [NotNullValidator()]
        public DateTime TimestampUtc
        {
            get
            {
                return this._TimestampUtc;
            }
            set
            {
                if (this._TimestampUtc != value)
                {
                    this.OnTimestampUtcChanging(value);
                    this.SendPropertyChanging("TimestampUtc");
                    this._TimestampUtc = value;
                    this.SendPropertyChanged("TimestampUtc");
                    this.OnTimestampUtcChanged();
                }
            }
        }

        public string EnvironmentJson
        {
            get
            {
                return this._EnvironmentJson;
            }
            set
            {
                if (this._EnvironmentJson != value)
                {
                    this.OnEnvironmentJsonChanging(value);
                    this.SendPropertyChanging("EnvironmentJson");
                    this._EnvironmentJson = value;
                    this.SendPropertyChanged("EnvironmentJson");
                    this.OnEnvironmentJsonChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 200,  RangeBoundaryType.Inclusive)]
        [NotNullValidator()]
        public string SchemaVersion
        {
            get
            {
                return this._SchemaVersion;
            }
            set
            {
                if (this._SchemaVersion != value)
                {
                    this.OnSchemaVersionChanging(value);
                    this.SendPropertyChanging("SchemaVersion");
                    this._SchemaVersion = value;
                    this.SendPropertyChanged("SchemaVersion");
                    this.OnSchemaVersionChanged();
                }
            }
        }


        public virtual ICollection<ExecutionResult> ExecutionResults
        {
            get
            {
                return this._ExecutionResults;
            }
            set
            {
                this._ExecutionResults = value;
            }
        }


        public virtual SourceSnapshot SourceSnapshot
        {
            get
            {
                return this._SourceSnapshot;
            }
            set
            {
                if (this._SourceSnapshot != value)
                {
                    this.OnSourceSnapshotChanging(value);
                    this.SendPropertyChanging("SourceSnapshot");
                    this._SourceSnapshot = value;
                    this.SendPropertyChanged("SourceSnapshot");
                    this.OnSourceSnapshotChanged();
                }
            }
        }


        public virtual SampleRun SampleRun
        {
            get
            {
                return this._SampleRun;
            }
            set
            {
                if (this._SampleRun != value)
                {
                    this.OnSampleRunChanging(value);
                    this.SendPropertyChanging("SampleRun");
                    this._SampleRun = value;
                    this.SendPropertyChanged("SampleRun");
                    this.OnSampleRunChanged();
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();
        partial void OnIdChanging(Guid value);

        partial void OnIdChanged();
        partial void OnSnapshotIdChanging(Guid value);

        partial void OnSnapshotIdChanged();
        partial void OnSampleRunIdChanging(Guid value);

        partial void OnSampleRunIdChanged();
        partial void OnTimestampUtcChanging(DateTime value);

        partial void OnTimestampUtcChanged();
        partial void OnEnvironmentJsonChanging(string value);

        partial void OnEnvironmentJsonChanged();
        partial void OnSchemaVersionChanging(string value);

        partial void OnSchemaVersionChanged();
        partial void OnSourceSnapshotChanging(SourceSnapshot value);

        partial void OnSourceSnapshotChanged();
        partial void OnSampleRunChanging(SampleRun value);

        partial void OnSampleRunChanged();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
