//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 1.25
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.Practices.EnterpriseLibrary.Validation.Validators;

namespace ITCompanionAI.Entities
{
    public partial class ReviewIssue : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private Guid _Id;

        private Guid _ReviewItemId;

        private string _Code;

        private string _Severity;

        private string _RelatedMemberUid;

        private string _Details;

        private ReviewItem _ReviewItem;

        public ReviewIssue()
        {
            OnCreated();
        }

        [NotNullValidator()]
        public Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging("Id");
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

        [NotNullValidator()]
        public Guid ReviewItemId
        {
            get
            {
                return this._ReviewItemId;
            }
            set
            {
                if (this._ReviewItemId != value)
                {
                    this.OnReviewItemIdChanging(value);
                    this.SendPropertyChanging("ReviewItemId");
                    this._ReviewItemId = value;
                    this.SendPropertyChanged("ReviewItemId");
                    this.OnReviewItemIdChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 200,  RangeBoundaryType.Inclusive)]
        public string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                if (this._Code != value)
                {
                    this.OnCodeChanging(value);
                    this.SendPropertyChanging("Code");
                    this._Code = value;
                    this.SendPropertyChanged("Code");
                    this.OnCodeChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 50,  RangeBoundaryType.Inclusive)]
        public string Severity
        {
            get
            {
                return this._Severity;
            }
            set
            {
                if (this._Severity != value)
                {
                    this.OnSeverityChanging(value);
                    this.SendPropertyChanging("Severity");
                    this._Severity = value;
                    this.SendPropertyChanged("Severity");
                    this.OnSeverityChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 1000,  RangeBoundaryType.Inclusive)]
        public string RelatedMemberUid
        {
            get
            {
                return this._RelatedMemberUid;
            }
            set
            {
                if (this._RelatedMemberUid != value)
                {
                    this.OnRelatedMemberUidChanging(value);
                    this.SendPropertyChanging("RelatedMemberUid");
                    this._RelatedMemberUid = value;
                    this.SendPropertyChanged("RelatedMemberUid");
                    this.OnRelatedMemberUidChanged();
                }
            }
        }

        public string Details
        {
            get
            {
                return this._Details;
            }
            set
            {
                if (this._Details != value)
                {
                    this.OnDetailsChanging(value);
                    this.SendPropertyChanging("Details");
                    this._Details = value;
                    this.SendPropertyChanged("Details");
                    this.OnDetailsChanged();
                }
            }
        }


        public virtual ReviewItem ReviewItem
        {
            get
            {
                return this._ReviewItem;
            }
            set
            {
                if (this._ReviewItem != value)
                {
                    this.OnReviewItemChanging(value);
                    this.SendPropertyChanging("ReviewItem");
                    this._ReviewItem = value;
                    this.SendPropertyChanged("ReviewItem");
                    this.OnReviewItemChanged();
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();
        partial void OnIdChanging(Guid value);

        partial void OnIdChanged();
        partial void OnReviewItemIdChanging(Guid value);

        partial void OnReviewItemIdChanged();
        partial void OnCodeChanging(string value);

        partial void OnCodeChanged();
        partial void OnSeverityChanging(string value);

        partial void OnSeverityChanged();
        partial void OnRelatedMemberUidChanging(string value);

        partial void OnRelatedMemberUidChanged();
        partial void OnDetailsChanging(string value);

        partial void OnDetailsChanged();
        partial void OnReviewItemChanging(ReviewItem value);

        partial void OnReviewItemChanged();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
