//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 1.25
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.Practices.EnterpriseLibrary.Validation.Validators;

namespace ITCompanionAI.Entities
{
    public partial class SnapshotDiff : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private Guid _Id;

        private Guid _OldSnapshotId;

        private Guid _NewSnapshotId;

        private DateTime _TimestampUtc;

        private string _SchemaVersion;

        private ICollection<ApiMemberDiff> _ApiMemberDiffs;

        private ICollection<ApiTypeDiff> _ApiTypeDiffs;

        private ICollection<DocPageDiff> _DocPageDiffs;

        private SourceSnapshot _SourceSnapshot_OldSnapshotId;

        private SourceSnapshot _SourceSnapshot_NewSnapshotId;

        public SnapshotDiff()
        {
            this._ApiMemberDiffs = new List<ApiMemberDiff>();
            this._ApiTypeDiffs = new List<ApiTypeDiff>();
            this._DocPageDiffs = new List<DocPageDiff>();
            OnCreated();
        }

        [NotNullValidator()]
        public Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging("Id");
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

        [NotNullValidator()]
        public Guid OldSnapshotId
        {
            get
            {
                return this._OldSnapshotId;
            }
            set
            {
                if (this._OldSnapshotId != value)
                {
                    this.OnOldSnapshotIdChanging(value);
                    this.SendPropertyChanging("OldSnapshotId");
                    this._OldSnapshotId = value;
                    this.SendPropertyChanged("OldSnapshotId");
                    this.OnOldSnapshotIdChanged();
                }
            }
        }

        [NotNullValidator()]
        public Guid NewSnapshotId
        {
            get
            {
                return this._NewSnapshotId;
            }
            set
            {
                if (this._NewSnapshotId != value)
                {
                    this.OnNewSnapshotIdChanging(value);
                    this.SendPropertyChanging("NewSnapshotId");
                    this._NewSnapshotId = value;
                    this.SendPropertyChanged("NewSnapshotId");
                    this.OnNewSnapshotIdChanged();
                }
            }
        }

        [NotNullValidator()]
        public DateTime TimestampUtc
        {
            get
            {
                return this._TimestampUtc;
            }
            set
            {
                if (this._TimestampUtc != value)
                {
                    this.OnTimestampUtcChanging(value);
                    this.SendPropertyChanging("TimestampUtc");
                    this._TimestampUtc = value;
                    this.SendPropertyChanged("TimestampUtc");
                    this.OnTimestampUtcChanged();
                }
            }
        }

        [StringLengthValidator(0,  RangeBoundaryType.Ignore, 200,  RangeBoundaryType.Inclusive)]
        [NotNullValidator()]
        public string SchemaVersion
        {
            get
            {
                return this._SchemaVersion;
            }
            set
            {
                if (this._SchemaVersion != value)
                {
                    this.OnSchemaVersionChanging(value);
                    this.SendPropertyChanging("SchemaVersion");
                    this._SchemaVersion = value;
                    this.SendPropertyChanged("SchemaVersion");
                    this.OnSchemaVersionChanged();
                }
            }
        }


        public virtual ICollection<ApiMemberDiff> ApiMemberDiffs
        {
            get
            {
                return this._ApiMemberDiffs;
            }
            set
            {
                this._ApiMemberDiffs = value;
            }
        }


        public virtual ICollection<ApiTypeDiff> ApiTypeDiffs
        {
            get
            {
                return this._ApiTypeDiffs;
            }
            set
            {
                this._ApiTypeDiffs = value;
            }
        }


        public virtual ICollection<DocPageDiff> DocPageDiffs
        {
            get
            {
                return this._DocPageDiffs;
            }
            set
            {
                this._DocPageDiffs = value;
            }
        }


        public virtual SourceSnapshot SourceSnapshot_OldSnapshotId
        {
            get
            {
                return this._SourceSnapshot_OldSnapshotId;
            }
            set
            {
                if (this._SourceSnapshot_OldSnapshotId != value)
                {
                    this.OnSourceSnapshot_OldSnapshotIdChanging(value);
                    this.SendPropertyChanging("SourceSnapshot_OldSnapshotId");
                    this._SourceSnapshot_OldSnapshotId = value;
                    this.SendPropertyChanged("SourceSnapshot_OldSnapshotId");
                    this.OnSourceSnapshot_OldSnapshotIdChanged();
                }
            }
        }


        public virtual SourceSnapshot SourceSnapshot_NewSnapshotId
        {
            get
            {
                return this._SourceSnapshot_NewSnapshotId;
            }
            set
            {
                if (this._SourceSnapshot_NewSnapshotId != value)
                {
                    this.OnSourceSnapshot_NewSnapshotIdChanging(value);
                    this.SendPropertyChanging("SourceSnapshot_NewSnapshotId");
                    this._SourceSnapshot_NewSnapshotId = value;
                    this.SendPropertyChanged("SourceSnapshot_NewSnapshotId");
                    this.OnSourceSnapshot_NewSnapshotIdChanged();
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();
        partial void OnIdChanging(Guid value);

        partial void OnIdChanged();
        partial void OnOldSnapshotIdChanging(Guid value);

        partial void OnOldSnapshotIdChanged();
        partial void OnNewSnapshotIdChanging(Guid value);

        partial void OnNewSnapshotIdChanged();
        partial void OnTimestampUtcChanging(DateTime value);

        partial void OnTimestampUtcChanged();
        partial void OnSchemaVersionChanging(string value);

        partial void OnSchemaVersionChanged();
        partial void OnSourceSnapshot_OldSnapshotIdChanging(SourceSnapshot value);

        partial void OnSourceSnapshot_OldSnapshotIdChanged();
        partial void OnSourceSnapshot_NewSnapshotIdChanging(SourceSnapshot value);

        partial void OnSourceSnapshot_NewSnapshotIdChanged();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
