// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.Data.SqlTypes;
using Microsoft.EntityFrameworkCore;

namespace ITCompanionAI;

[Table("rag_chunk")]
[Index("Kind", Name = "ix_rag_chunk_kind")]
[Index("ChunkUid", Name = "uq_rag_chunk_uid", IsUnique = true)]
public partial class RagChunk
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("rag_run_id")]
    public Guid RagRunId { get; set; }

    [Required]
    [Column("chunk_uid")]
    [StringLength(1000)]
    public string ChunkUid { get; set; }

    [Column("kind")]
    [StringLength(100)]
    public string Kind { get; set; }

    [Column("text")]
    public string Text { get; set; }

    [Column("metadata_json")]
    public string MetadataJson { get; set; }

    [Column("chunk_hash")]
    [StringLength(400)]
    public string ChunkHash { get; set; }

    [Column("token_count")]
    [StringLength(10)]
    public string TokenCount { get; set; }

    [Column("source_model")]
    [StringLength(50)]
    public string SourceModel { get; set; }

    [Column("embedding_version")]
    [StringLength(10)]
    public string EmbeddingVersion { get; set; }

    [Column("distance_metric")]
    [StringLength(50)]
    public string DistanceMetric { get; set; }

    [Column("content_type")]
    [StringLength(50)]
    public string ContentType { get; set; }

    [Column("embedding")]
    [MaxLength(1024)]
    public SqlVector<float>? Embedding { get; set; }
}