// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITCompanionAI;

[Table("review_run")]
[Index("SnapshotId", "TimestampUtc", Name = "ix_review_run_snapshot_time")]
public partial class ReviewRun
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("snapshot_id")]
    public Guid SnapshotId { get; set; }

    [Column("timestamp_utc")]
    public DateTime TimestampUtc { get; set; }

    [Required]
    [Column("schema_version")]
    [StringLength(200)]
    public string SchemaVersion { get; set; }
}