// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITCompanionAI;

[Table("review_issue")]
[Index("Severity", Name = "ix_review_issue_severity")]
public partial class ReviewIssue
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("review_item_id")]
    public Guid ReviewItemId { get; set; }

    [Column("code")]
    [StringLength(200)]
    public string Code { get; set; }

    [Column("severity")]
    [StringLength(50)]
    public string Severity { get; set; }

    [Column("related_member_uid")]
    [StringLength(1000)]
    public string RelatedMemberUid { get; set; }

    [Column("details")]
    public string Details { get; set; }
}