//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 1/8/2026 10:40:40 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace ITCompanionAI.EFModels;

public partial class SampleApiMemberLink : INotifyPropertyChanging, INotifyPropertyChanged {

    private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

    private Guid _Id;

    private Guid _SampleId;

    private string _MemberUid;

    public SampleApiMemberLink()
    {
        OnCreated();
    }

    public Guid Id
    {
        get
        {
            return this._Id;
        }
        set
        {
            if (this._Id != value)
            {
                this.SendPropertyChanging("Id");
                this._Id = value;
                this.SendPropertyChanged("Id");
            }
        }
    }

    public Guid SampleId
    {
        get
        {
            return this._SampleId;
        }
        set
        {
            if (this._SampleId != value)
            {
                this.SendPropertyChanging("SampleId");
                this._SampleId = value;
                this.SendPropertyChanged("SampleId");
            }
        }
    }

    public string MemberUid
    {
        get
        {
            return this._MemberUid;
        }
        set
        {
            if (this._MemberUid != value)
            {
                this.SendPropertyChanging("MemberUid");
                this._MemberUid = value;
                this.SendPropertyChanged("MemberUid");
            }
        }
    }

    #region Extensibility Method Definitions

    partial void OnCreated();

    #endregion

    public virtual event PropertyChangingEventHandler PropertyChanging;

    public virtual event PropertyChangedEventHandler PropertyChanged;

    protected virtual void SendPropertyChanging()
    {
        var handler = this.PropertyChanging;
        if (handler != null)
            handler(this, emptyChangingEventArgs);
    }

    protected virtual void SendPropertyChanging(System.String propertyName) 
    {
        var handler = this.PropertyChanging;
        if (handler != null)
            handler(this, new PropertyChangingEventArgs(propertyName));
    }

    protected virtual void SendPropertyChanged(System.String propertyName)
    {
        var handler = this.PropertyChanged;
        if (handler != null)
            handler(this, new PropertyChangedEventArgs(propertyName));
    }
}