// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITCompanionAI;

[Table("sample")]
[Index("FeatureUid", Name = "ix_sample_feature_uid")]
[Index("SampleUid", Name = "uq_sample_uid", IsUnique = true)]
public partial class Sample
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("sample_run_id")]
    public Guid SampleRunId { get; set; }

    [Required]
    [Column("sample_uid")]
    [StringLength(1000)]
    public string SampleUid { get; set; }

    [Column("feature_uid")]
    [StringLength(1000)]
    public string FeatureUid { get; set; }

    [Column("language")]
    [StringLength(200)]
    public string Language { get; set; }

    [Column("code")]
    public string Code { get; set; }

    [Column("entry_point")]
    [StringLength(400)]
    public string EntryPoint { get; set; }

    [Column("target_framework")]
    [StringLength(200)]
    public string TargetFramework { get; set; }

    [Column("package_references")]
    public string PackageReferences { get; set; }

    [Column("derived_from_code_uid")]
    [StringLength(1000)]
    public string DerivedFromCodeUid { get; set; }

    [Column("tags")]
    public string Tags { get; set; }
}