// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITCompanionAI;

[Table("sample_api_member_link")]
[Index("MemberUid", Name = "ix_sample_api_member_link_member")]
public partial class SampleApiMemberLink
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("sample_id")]
    public Guid SampleId { get; set; }

    [Required]
    [Column("member_uid")]
    [StringLength(1000)]
    public string MemberUid { get; set; }
}