// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITCompanionAI;

[Table("semantic_identity")]
[Index("Kind", "Uid", Name = "ix_semantic_identity_kind_uid_hash")]
public partial class SemanticIdentity
{
    [Key]
    [Required]
    [Column("uid")]
    [StringLength(1000)]
    public string Uid { get; set; }

    
    [Column("uid_hash")]
    [MaxLength(32)]
    public byte[] UidHash { get; set; }

    [Required]
    [Column("kind")]
    [StringLength(50)]
    public string Kind { get; set; }

    [Column("created_utc")]
    public DateTime CreatedUtc { get; set; }

    [Column("notes")]
    public string Notes { get; set; }
}