//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 1/8/2026 10:40:40 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace ITCompanionAI.EFModels;

public partial class SnapshotDiff : INotifyPropertyChanging, INotifyPropertyChanged {

    private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

    private Guid _Id;

    private Guid _OldSnapshotId;

    private Guid _NewSnapshotId;

    private DateTime _TimestampUtc;

    private string _SchemaVersion;

    public SnapshotDiff()
    {
        OnCreated();
    }

    public Guid Id
    {
        get
        {
            return this._Id;
        }
        set
        {
            if (this._Id != value)
            {
                this.SendPropertyChanging("Id");
                this._Id = value;
                this.SendPropertyChanged("Id");
            }
        }
    }

    public Guid OldSnapshotId
    {
        get
        {
            return this._OldSnapshotId;
        }
        set
        {
            if (this._OldSnapshotId != value)
            {
                this.SendPropertyChanging("OldSnapshotId");
                this._OldSnapshotId = value;
                this.SendPropertyChanged("OldSnapshotId");
            }
        }
    }

    public Guid NewSnapshotId
    {
        get
        {
            return this._NewSnapshotId;
        }
        set
        {
            if (this._NewSnapshotId != value)
            {
                this.SendPropertyChanging("NewSnapshotId");
                this._NewSnapshotId = value;
                this.SendPropertyChanged("NewSnapshotId");
            }
        }
    }

    public DateTime TimestampUtc
    {
        get
        {
            return this._TimestampUtc;
        }
        set
        {
            if (this._TimestampUtc != value)
            {
                this.SendPropertyChanging("TimestampUtc");
                this._TimestampUtc = value;
                this.SendPropertyChanged("TimestampUtc");
            }
        }
    }

    public string SchemaVersion
    {
        get
        {
            return this._SchemaVersion;
        }
        set
        {
            if (this._SchemaVersion != value)
            {
                this.SendPropertyChanging("SchemaVersion");
                this._SchemaVersion = value;
                this.SendPropertyChanged("SchemaVersion");
            }
        }
    }

    #region Extensibility Method Definitions

    partial void OnCreated();

    #endregion

    public virtual event PropertyChangingEventHandler PropertyChanging;

    public virtual event PropertyChangedEventHandler PropertyChanged;

    protected virtual void SendPropertyChanging()
    {
        var handler = this.PropertyChanging;
        if (handler != null)
            handler(this, emptyChangingEventArgs);
    }

    protected virtual void SendPropertyChanging(System.String propertyName) 
    {
        var handler = this.PropertyChanging;
        if (handler != null)
            handler(this, new PropertyChangingEventArgs(propertyName));
    }

    protected virtual void SendPropertyChanged(System.String propertyName)
    {
        var handler = this.PropertyChanged;
        if (handler != null)
            handler(this, new PropertyChangedEventArgs(propertyName));
    }
}