// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITCompanionAI;

[Table("source_snapshot")]
[Index("IngestionRunId", "SnapshotUid", Name = "ix_source_snapshot_ingestion_run")]
[Index("IngestionRunId", "SnapshotUidHash", Name = "ix_source_snapshot_ingestion_run_hash")]
public partial class SourceSnapshot
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("ingestion_run_id")]
    public Guid IngestionRunId { get; set; }

    [Required]
    [Column("snapshot_uid")]
    [StringLength(200)]
    public string SnapshotUid { get; set; }

    [Column("repo_url")]
    public string RepoUrl { get; set; }

    [Column("branch")]
    [StringLength(200)]
    public string Branch { get; set; }

    [Column("repo_commit")]
    [StringLength(200)]
    public string RepoCommit { get; set; }

    [Column("language")]
    [StringLength(200)]
    public string Language { get; set; }

    [Column("package_name")]
    [StringLength(200)]
    public string PackageName { get; set; }

    [Column("package_version")]
    [StringLength(200)]
    public string PackageVersion { get; set; }

    [Column("config_json")]
    public string ConfigJson { get; set; }

    [Column("snapshot_uid_hash")]
    [MaxLength(32)]
    public byte[] SnapshotUidHash { get; set; }

    [InverseProperty("SourceSnapshot")]
    public virtual ICollection<DocPage> DocPages { get; set; } = new List<DocPage>();
}