// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ITCompanionAI
{
    public partial class sp_CheckTemporalConsistencyResult
    {
        [StringLength(8)]
        public string table_name { get; set; }
        [StringLength(1000)]
        public string semantic_uid { get; set; }
    }
}
