// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ITCompanionAI
{
    public partial class sp_GetChangesInIngestionRunResult
    {
        [StringLength(8)]
        public string artifact_kind { get; set; }
        [StringLength(1000)]
        public string semantic_uid { get; set; }
        public int version_number { get; set; }
        public DateTime valid_from_utc { get; set; }
        public DateTime? valid_to_utc { get; set; }
    }
}
