// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ITCompanionAI
{
    public partial class sp_GetSemanticHistoryResult
    {
        public Guid id { get; set; }
        public Guid? api_type_id { get; set; }
        [StringLength(1000)]
        public string semantic_uid { get; set; }
        public Guid truth_run_id { get; set; }
        [StringLength(400)]
        public string name { get; set; }
        [StringLength(200)]
        public string language { get; set; }
        [StringLength(2147483647)]
        public string description { get; set; }
        [StringLength(2147483647)]
        public string tags { get; set; }
        public int version_number { get; set; }
        public Guid created_ingestion_run_id { get; set; }
        public Guid updated_ingestion_run_id { get; set; }
        public Guid? removed_ingestion_run_id { get; set; }
        public DateTime valid_from_utc { get; set; }
        public DateTime? valid_to_utc { get; set; }
        public bool is_active { get; set; }
        public byte[] content_hash { get; set; }
        public byte[] semantic_uid_hash { get; set; }
    }
}
