// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ITCompanionAI
{
    public partial class sp_VerifyIngestionRunResult
    {
        [StringLength(200)]
        public string category { get; set; }
        [StringLength(2147483647)]
        public string detail { get; set; }
    }
}
