//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 1/8/2026 10:40:40 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace ITCompanionAI.EFModels;

public partial class VApiMemberCurrent : INotifyPropertyChanging, INotifyPropertyChanged {

    private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

    private Guid _Id;

    private string _SemanticUid;

    private Guid _ApiFeatureId;

    private string _Name;

    private string _Kind;

    private string _MethodKind;

    private string _Accessibility;

    private bool? _IsStatic;

    private bool? _IsExtensionMethod;

    private bool? _IsAsync;

    private bool? _IsVirtual;

    private bool? _IsOverride;

    private bool? _IsAbstract;

    private bool? _IsSealed;

    private bool? _IsReadonly;

    private bool? _IsConst;

    private bool? _IsUnsafe;

    private string _ReturnTypeUid;

    private string _ReturnNullable;

    private string _GenericParameters;

    private string _GenericConstraints;

    private string _Summary;

    private string _Remarks;

    private string _Attributes;

    private string _SourceFilePath;

    private int? _SourceStartLine;

    private int? _SourceEndLine;

    private byte[] _MemberUidHash;

    private int _VersionNumber;

    private Guid _CreatedIngestionRunId;

    private Guid? _UpdatedIngestionRunId;

    private Guid? _RemovedIngestionRunId;

    private DateTime _ValidFromUtc;

    private DateTime? _ValidToUtc;

    private bool _IsActive;

    private byte[] _ContentHash;

    private byte[] _SemanticUidHash;

    public VApiMemberCurrent()
    {
        OnCreated();
    }

    public Guid Id
    {
        get
        {
            return this._Id;
        }
        set
        {
            if (this._Id != value)
            {
                this.SendPropertyChanging("Id");
                this._Id = value;
                this.SendPropertyChanged("Id");
            }
        }
    }

    public string SemanticUid
    {
        get
        {
            return this._SemanticUid;
        }
        set
        {
            if (this._SemanticUid != value)
            {
                this.SendPropertyChanging("SemanticUid");
                this._SemanticUid = value;
                this.SendPropertyChanged("SemanticUid");
            }
        }
    }

    public Guid ApiFeatureId
    {
        get
        {
            return this._ApiFeatureId;
        }
        set
        {
            if (this._ApiFeatureId != value)
            {
                this.SendPropertyChanging("ApiFeatureId");
                this._ApiFeatureId = value;
                this.SendPropertyChanged("ApiFeatureId");
            }
        }
    }

    public string Name
    {
        get
        {
            return this._Name;
        }
        set
        {
            if (this._Name != value)
            {
                this.SendPropertyChanging("Name");
                this._Name = value;
                this.SendPropertyChanged("Name");
            }
        }
    }

    public string Kind
    {
        get
        {
            return this._Kind;
        }
        set
        {
            if (this._Kind != value)
            {
                this.SendPropertyChanging("Kind");
                this._Kind = value;
                this.SendPropertyChanged("Kind");
            }
        }
    }

    public string MethodKind
    {
        get
        {
            return this._MethodKind;
        }
        set
        {
            if (this._MethodKind != value)
            {
                this.SendPropertyChanging("MethodKind");
                this._MethodKind = value;
                this.SendPropertyChanged("MethodKind");
            }
        }
    }

    public string Accessibility
    {
        get
        {
            return this._Accessibility;
        }
        set
        {
            if (this._Accessibility != value)
            {
                this.SendPropertyChanging("Accessibility");
                this._Accessibility = value;
                this.SendPropertyChanged("Accessibility");
            }
        }
    }

    public bool? IsStatic
    {
        get
        {
            return this._IsStatic;
        }
        set
        {
            if (this._IsStatic != value)
            {
                this.SendPropertyChanging("IsStatic");
                this._IsStatic = value;
                this.SendPropertyChanged("IsStatic");
            }
        }
    }

    public bool? IsExtensionMethod
    {
        get
        {
            return this._IsExtensionMethod;
        }
        set
        {
            if (this._IsExtensionMethod != value)
            {
                this.SendPropertyChanging("IsExtensionMethod");
                this._IsExtensionMethod = value;
                this.SendPropertyChanged("IsExtensionMethod");
            }
        }
    }

    public bool? IsAsync
    {
        get
        {
            return this._IsAsync;
        }
        set
        {
            if (this._IsAsync != value)
            {
                this.SendPropertyChanging("IsAsync");
                this._IsAsync = value;
                this.SendPropertyChanged("IsAsync");
            }
        }
    }

    public bool? IsVirtual
    {
        get
        {
            return this._IsVirtual;
        }
        set
        {
            if (this._IsVirtual != value)
            {
                this.SendPropertyChanging("IsVirtual");
                this._IsVirtual = value;
                this.SendPropertyChanged("IsVirtual");
            }
        }
    }

    public bool? IsOverride
    {
        get
        {
            return this._IsOverride;
        }
        set
        {
            if (this._IsOverride != value)
            {
                this.SendPropertyChanging("IsOverride");
                this._IsOverride = value;
                this.SendPropertyChanged("IsOverride");
            }
        }
    }

    public bool? IsAbstract
    {
        get
        {
            return this._IsAbstract;
        }
        set
        {
            if (this._IsAbstract != value)
            {
                this.SendPropertyChanging("IsAbstract");
                this._IsAbstract = value;
                this.SendPropertyChanged("IsAbstract");
            }
        }
    }

    public bool? IsSealed
    {
        get
        {
            return this._IsSealed;
        }
        set
        {
            if (this._IsSealed != value)
            {
                this.SendPropertyChanging("IsSealed");
                this._IsSealed = value;
                this.SendPropertyChanged("IsSealed");
            }
        }
    }

    public bool? IsReadonly
    {
        get
        {
            return this._IsReadonly;
        }
        set
        {
            if (this._IsReadonly != value)
            {
                this.SendPropertyChanging("IsReadonly");
                this._IsReadonly = value;
                this.SendPropertyChanged("IsReadonly");
            }
        }
    }

    public bool? IsConst
    {
        get
        {
            return this._IsConst;
        }
        set
        {
            if (this._IsConst != value)
            {
                this.SendPropertyChanging("IsConst");
                this._IsConst = value;
                this.SendPropertyChanged("IsConst");
            }
        }
    }

    public bool? IsUnsafe
    {
        get
        {
            return this._IsUnsafe;
        }
        set
        {
            if (this._IsUnsafe != value)
            {
                this.SendPropertyChanging("IsUnsafe");
                this._IsUnsafe = value;
                this.SendPropertyChanged("IsUnsafe");
            }
        }
    }

    public string ReturnTypeUid
    {
        get
        {
            return this._ReturnTypeUid;
        }
        set
        {
            if (this._ReturnTypeUid != value)
            {
                this.SendPropertyChanging("ReturnTypeUid");
                this._ReturnTypeUid = value;
                this.SendPropertyChanged("ReturnTypeUid");
            }
        }
    }

    public string ReturnNullable
    {
        get
        {
            return this._ReturnNullable;
        }
        set
        {
            if (this._ReturnNullable != value)
            {
                this.SendPropertyChanging("ReturnNullable");
                this._ReturnNullable = value;
                this.SendPropertyChanged("ReturnNullable");
            }
        }
    }

    public string GenericParameters
    {
        get
        {
            return this._GenericParameters;
        }
        set
        {
            if (this._GenericParameters != value)
            {
                this.SendPropertyChanging("GenericParameters");
                this._GenericParameters = value;
                this.SendPropertyChanged("GenericParameters");
            }
        }
    }

    public string GenericConstraints
    {
        get
        {
            return this._GenericConstraints;
        }
        set
        {
            if (this._GenericConstraints != value)
            {
                this.SendPropertyChanging("GenericConstraints");
                this._GenericConstraints = value;
                this.SendPropertyChanged("GenericConstraints");
            }
        }
    }

    public string Summary
    {
        get
        {
            return this._Summary;
        }
        set
        {
            if (this._Summary != value)
            {
                this.SendPropertyChanging("Summary");
                this._Summary = value;
                this.SendPropertyChanged("Summary");
            }
        }
    }

    public string Remarks
    {
        get
        {
            return this._Remarks;
        }
        set
        {
            if (this._Remarks != value)
            {
                this.SendPropertyChanging("Remarks");
                this._Remarks = value;
                this.SendPropertyChanged("Remarks");
            }
        }
    }

    public string Attributes
    {
        get
        {
            return this._Attributes;
        }
        set
        {
            if (this._Attributes != value)
            {
                this.SendPropertyChanging("Attributes");
                this._Attributes = value;
                this.SendPropertyChanged("Attributes");
            }
        }
    }

    public string SourceFilePath
    {
        get
        {
            return this._SourceFilePath;
        }
        set
        {
            if (this._SourceFilePath != value)
            {
                this.SendPropertyChanging("SourceFilePath");
                this._SourceFilePath = value;
                this.SendPropertyChanged("SourceFilePath");
            }
        }
    }

    public int? SourceStartLine
    {
        get
        {
            return this._SourceStartLine;
        }
        set
        {
            if (this._SourceStartLine != value)
            {
                this.SendPropertyChanging("SourceStartLine");
                this._SourceStartLine = value;
                this.SendPropertyChanged("SourceStartLine");
            }
        }
    }

    public int? SourceEndLine
    {
        get
        {
            return this._SourceEndLine;
        }
        set
        {
            if (this._SourceEndLine != value)
            {
                this.SendPropertyChanging("SourceEndLine");
                this._SourceEndLine = value;
                this.SendPropertyChanged("SourceEndLine");
            }
        }
    }

    public byte[] MemberUidHash
    {
        get
        {
            return this._MemberUidHash;
        }
        set
        {
            if (this._MemberUidHash != value)
            {
                this.SendPropertyChanging("MemberUidHash");
                this._MemberUidHash = value;
                this.SendPropertyChanged("MemberUidHash");
            }
        }
    }

    public int VersionNumber
    {
        get
        {
            return this._VersionNumber;
        }
        set
        {
            if (this._VersionNumber != value)
            {
                this.SendPropertyChanging("VersionNumber");
                this._VersionNumber = value;
                this.SendPropertyChanged("VersionNumber");
            }
        }
    }

    public Guid CreatedIngestionRunId
    {
        get
        {
            return this._CreatedIngestionRunId;
        }
        set
        {
            if (this._CreatedIngestionRunId != value)
            {
                this.SendPropertyChanging("CreatedIngestionRunId");
                this._CreatedIngestionRunId = value;
                this.SendPropertyChanged("CreatedIngestionRunId");
            }
        }
    }

    public Guid? UpdatedIngestionRunId
    {
        get
        {
            return this._UpdatedIngestionRunId;
        }
        set
        {
            if (this._UpdatedIngestionRunId != value)
            {
                this.SendPropertyChanging("UpdatedIngestionRunId");
                this._UpdatedIngestionRunId = value;
                this.SendPropertyChanged("UpdatedIngestionRunId");
            }
        }
    }

    public Guid? RemovedIngestionRunId
    {
        get
        {
            return this._RemovedIngestionRunId;
        }
        set
        {
            if (this._RemovedIngestionRunId != value)
            {
                this.SendPropertyChanging("RemovedIngestionRunId");
                this._RemovedIngestionRunId = value;
                this.SendPropertyChanged("RemovedIngestionRunId");
            }
        }
    }

    public DateTime ValidFromUtc
    {
        get
        {
            return this._ValidFromUtc;
        }
        set
        {
            if (this._ValidFromUtc != value)
            {
                this.SendPropertyChanging("ValidFromUtc");
                this._ValidFromUtc = value;
                this.SendPropertyChanged("ValidFromUtc");
            }
        }
    }

    public DateTime? ValidToUtc
    {
        get
        {
            return this._ValidToUtc;
        }
        set
        {
            if (this._ValidToUtc != value)
            {
                this.SendPropertyChanging("ValidToUtc");
                this._ValidToUtc = value;
                this.SendPropertyChanged("ValidToUtc");
            }
        }
    }

    public bool IsActive
    {
        get
        {
            return this._IsActive;
        }
        set
        {
            if (this._IsActive != value)
            {
                this.SendPropertyChanging("IsActive");
                this._IsActive = value;
                this.SendPropertyChanged("IsActive");
            }
        }
    }

    public byte[] ContentHash
    {
        get
        {
            return this._ContentHash;
        }
        set
        {
            if (this._ContentHash != value)
            {
                this.SendPropertyChanging("ContentHash");
                this._ContentHash = value;
                this.SendPropertyChanged("ContentHash");
            }
        }
    }

    public byte[] SemanticUidHash
    {
        get
        {
            return this._SemanticUidHash;
        }
        set
        {
            if (this._SemanticUidHash != value)
            {
                this.SendPropertyChanging("SemanticUidHash");
                this._SemanticUidHash = value;
                this.SendPropertyChanged("SemanticUidHash");
            }
        }
    }

    #region Extensibility Method Definitions

    partial void OnCreated();

    #endregion

    public virtual event PropertyChangingEventHandler PropertyChanging;

    public virtual event PropertyChangedEventHandler PropertyChanged;

    protected virtual void SendPropertyChanging()
    {
        var handler = this.PropertyChanging;
        if (handler != null)
            handler(this, emptyChangingEventArgs);
    }

    protected virtual void SendPropertyChanging(System.String propertyName) 
    {
        var handler = this.PropertyChanging;
        if (handler != null)
            handler(this, new PropertyChangingEventArgs(propertyName));
    }

    protected virtual void SendPropertyChanged(System.String propertyName)
    {
        var handler = this.PropertyChanged;
        if (handler != null)
            handler(this, new PropertyChangedEventArgs(propertyName));
    }
}