// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITCompanionAI;

[Keyless]
public partial class VApiFeatureCurrent
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("api_type_id")]
    public Guid? ApiTypeId { get; set; }

    [Required]
    [Column("semantic_uid")]
    [StringLength(1000)]
    public string SemanticUid { get; set; }

    [Column("truth_run_id")]
    public Guid TruthRunId { get; set; }

    [Column("name")]
    [StringLength(400)]
    public string Name { get; set; }

    [Column("language")]
    [StringLength(200)]
    public string Language { get; set; }

    [Column("description")]
    public string Description { get; set; }

    [Column("tags")]
    public string Tags { get; set; }

    [Column("version_number")]
    public int VersionNumber { get; set; }

    [Column("created_ingestion_run_id")]
    public Guid CreatedIngestionRunId { get; set; }

    [Column("updated_ingestion_run_id")]
    public Guid UpdatedIngestionRunId { get; set; }

    [Column("removed_ingestion_run_id")]
    public Guid? RemovedIngestionRunId { get; set; }

    [Column("valid_from_utc")]
    public DateTime ValidFromUtc { get; set; }

    [Column("valid_to_utc")]
    public DateTime? ValidToUtc { get; set; }

    [Column("is_active")]
    public bool IsActive { get; set; }

    [Column("content_hash")]
    [MaxLength(32)]
    public byte[] ContentHash { get; set; }

    [Column("semantic_uid_hash")]
    [MaxLength(32)]
    public byte[] SemanticUidHash { get; set; }
}