// Project Name: LightweightAI.Core
// File Name: KsTest.cs
// Author: AutoGenerated
// License: All Rights Reserved. No use without consent.
// Do not remove file headers

namespace LightweightAI.Core.Engine.SlowDetectors;

/// <summary>
/// Placeholder Kolmogorov-Smirnov drift detector. Maintains two sliding windows and computes
/// an approximate KS statistic (currently stubbed returning 0) for future drift signaling.
/// </summary>
public sealed class KsTest
{
    public double UpdateAndScore(double value, DateTimeOffset nowUtc) => 0.0; // TODO: implement
}