// Project Name: LightweightAI.Core
// File Name: WebhookAlertSink.cs
// Author: AutoGenerated
// License: All Rights Reserved. No use without consent.
// Do not remove file headers

using System.Net.Http.Json;
using LightweightAI.Core.Abstractions;

namespace LightweightAI.Core.Engine.Alerts;

/// <summary>
/// Simple JSON POST webhook sink for alert forwarding.
/// </summary>
public sealed class WebhookAlertSink : IAlertSink, IDisposable
{
    public string Name => "webhook";
    private readonly HttpClient _http = new();
    private readonly string _url;

    public WebhookAlertSink(string url) => _url = url;

    public async Task SendAsync(ProvenancedDecision decision, CancellationToken ct = default)
    {
        await _http.PostAsJsonAsync(_url, decision, ct);
    }

    public void Dispose() => _http.Dispose();
}