name: Minimal File Manifest

permissions:
  contents: write

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  generate-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Generate minimal manifest
        run: |
          python scripts/generate_minimal_manifest.py
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/FILE_MANIFEST.md manifest/file-paths.txt manifest/html-urls.txt manifest/raw-urls.txt || true
          if ! git diff --cached --quiet; then
            git commit -m "chore: update minimal file manifest"
            git push
          else
            echo "No changes to commit."
          fi
